package com.richuang.os.nocode.tools;

import static com.richuang.os.nocode.tools.NocodeIntegrationSupport.*;

import static org.assertj.core.api.Assertions.*;

import com.richuang.os.nocode.api.*;
import com.richuang.os.nocode.application.service.application.ApplicationService;
import com.richuang.os.nocode.application.service.authorization.ApplicationAuthorizationService;
import com.richuang.os.nocode.application.service.resource.ApplicationReportValidator;
import com.richuang.os.nocode.application.service.resource.ApplicationResourceValidator;
import com.richuang.os.nocode.application.service.sharing.ObjectSharingService;
import com.richuang.os.nocode.runtime.service.application.ApplicationRuntimeService;
import com.richuang.os.nocode.runtime.service.record.RecordService;
import com.richuang.os.nocode.runtime.service.report.ApplicationReportService;

import org.junit.jupiter.api.*;
import org.springframework.transaction.support.TransactionTemplate;

import java.util.*;

/** 真实开发库的报表回归；每例整体回滚，DDL/授权/记录均归随机测试前缀。 */
class ReportIntegrationTest {
    private NocodeIntegrationSupport fixture;
    private ApplicationService apps;
    private ApplicationReportService reports;
    private RecordService records;
    private DataObjectApi objects;
    private int serial;

    @BeforeAll
    static void open() throws Exception {
        connect();
    }

    @AfterAll
    static void shutdown() {
        close();
    }

    @BeforeEach
    void setup() {
        fixture = new NocodeIntegrationSupport();
        fixture.name();
        apps = servicesContext.getBean(ApplicationService.class);
        reports = servicesContext.getBean(ApplicationReportService.class);
        records = servicesContext.getBean(RecordService.class);
        objects = servicesContext.getBean(DataObjectApi.class);
    }

    @AfterEach
    void cleanup() {
        fixture.clean();
    }

    private void rollback(Runnable action) {
        new TransactionTemplate(manager)
                .executeWithoutResult(
                        tx -> {
                            try {
                                action.run();
                            } finally {
                                tx.setRollbackOnly();
                            }
                        });
    }

    private DataCenter.Definition object(DataCenter.Definition target, String relationKind) {
        return object(target, relationKind, false);
    }

    private DataCenter.Definition object(
            DataCenter.Definition target, String relationKind, boolean zoned) {
        if (zoned) {
            String name = "biz_" + fixture.prefix + "zoned" + serial++;
            jdbc.execute(
                    "CREATE TABLE public.\""
                            + name
                            + "\" (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name"
                            + " varchar(100),amount numeric(30,4),status varchar(100),booked"
                            + " timestamp with time zone,creator varchar(64) DEFAULT '',updater"
                            + " varchar(64) DEFAULT '',create_time timestamp NOT NULL DEFAULT"
                            + " CURRENT_TIMESTAMP,update_time timestamp NOT NULL DEFAULT"
                            + " CURRENT_TIMESTAMP,deleted smallint NOT NULL DEFAULT 0)");
            var check = tables.preflight("public", name);
            var adopted =
                    tables.adopt(
                            new DataCenter.Adoption(
                                    "public",
                                    name,
                                    fixture.prefix + "zoned",
                                    "带时区旧表",
                                    "name",
                                    check.fingerprint()),
                            10001);
            var plan =
                    publisher.plan(
                            new DataCenter.Revision(
                                    adopted.draft().id(), adopted.draft().lockVersion(), null),
                            10001);
            assertThat(plan.checks()).noneMatch(DataCenter.Check::blocking);
            assertThat(
                            publisher
                                    .execute(
                                            new DataCenter.ExecutePlan(plan.id(), "时区旧表纳管验收"),
                                            10001)
                                    .state())
                    .isEqualTo("SUCCEEDED");
            return objects.getPublished(adopted.draft().id());
        }
        String suffix = "report" + serial++;
        var request =
                new SaveObjectDraft(
                        null,
                        null,
                        fixture.prefix + suffix,
                        "报表回归",
                        null,
                        "biz_" + fixture.prefix + suffix,
                        "name",
                        List.of(
                                new FieldDefinition(
                                        "name", null, "name", "名称", "TEXT", 100, null, null, true,
                                        false, 0),
                                new FieldDefinition(
                                        "amount", null, "amount", "金额", "DECIMAL", null, 30, 4,
                                        false, false, 1),
                                new FieldDefinition(
                                        "status", null, "status", "状态", "TEXT", 100, null, null,
                                        false, false, 2),
                                new FieldDefinition(
                                        "booked",
                                        null,
                                        "booked",
                                        "日期",
                                        zoned ? "DATETIME" : "DATE",
                                        null,
                                        null,
                                        null,
                                        false,
                                        false,
                                        3)),
                        List.of());
        var relations =
                target == null
                        ? List.<DataCenter.Relation>of()
                        : List.of(
                                new DataCenter.Relation(
                                        null,
                                        "company",
                                        "所属公司",
                                        relationKind,
                                        target.objectId(),
                                        null,
                                        null,
                                        false,
                                        "RESTRICT"));
        var design =
                designs.save(
                        new DataCenter.SaveDesign(
                                request,
                                DataCenter.Settings.defaults(),
                                Map.of(),
                                relations,
                                List.of(),
                                List.of()),
                        10001);
        var plan =
                publisher.plan(
                        new DataCenter.Revision(
                                design.draft().id(), design.draft().lockVersion(), null),
                        10001);
        assertThat(plan.checks()).noneMatch(DataCenter.Check::blocking);
        assertThat(publisher.execute(new DataCenter.ExecutePlan(plan.id(), "报表测试"), 10001).state())
                .isEqualTo("SUCCEEDED");
        return objects.getPublished(design.draft().id());
    }

    private String field(DataCenter.Definition d, String code) {
        return d.fields().stream()
                .filter(
                        f ->
                                f.code().equals(code)
                                        || code.equals(
                                                d.fieldOptions()
                                                        .getOrDefault(
                                                                f.id(),
                                                                DataCenter.FieldOptions.defaults())
                                                        .columnName()))
                .findFirst()
                .orElseThrow()
                .id();
    }

    private ApplicationReports.Config config(
            DataCenter.Definition d, List<ApplicationReports.Dimension> dims) {
        return new ApplicationReports.Config(
                d.objectId(),
                dims,
                List.of(
                        new ApplicationReports.Metric("amount", "金额合计", "SUM", field(d, "amount")),
                        new ApplicationReports.Metric("count", "记录数", "COUNT", null),
                        new ApplicationReports.Metric(
                                "average", "平均金额", "AVG", field(d, "amount"))),
                Map.of(),
                List.of(field(d, "status")),
                field(d, "booked"),
                "Asia/Shanghai",
                dims.isEmpty() ? "METRIC" : "TABLE",
                null,
                false,
                30,
                null);
    }

    @Test
    void referenceIdsCannotBeUsedAsNumericMetrics() {
        rollback(
                () -> {
                    var target = object(null, null);
                    var source = object(target, "REFERENCE");
                    var reference = source.relations().getFirst().fieldId();
                    var validator = servicesContext.getBean(ApplicationReportValidator.class);
                    for (String operation : List.of("SUM", "AVG", "MIN", "MAX")) {
                        var config =
                                new ApplicationReports.Config(
                                        source.objectId(),
                                        List.of(),
                                        List.of(
                                                new ApplicationReports.Metric(
                                                        "wrong", "错误指标", operation, reference)),
                                        Map.of(),
                                        List.of(),
                                        null,
                                        "Asia/Shanghai",
                                        "METRIC",
                                        null,
                                        false,
                                        30,
                                        null);
                        assertThatThrownBy(
                                        () ->
                                                validator.normalize(
                                                        config,
                                                        Map.of(
                                                                source.objectId(),
                                                                source,
                                                                target.objectId(),
                                                                target)))
                                .hasMessageContaining("不能使用对象引用");
                    }
                });
    }

    private ApplicationCenter.Resource resource(String id, String kind, Object config) {
        return new ApplicationCenter.Resource(
                id,
                kind,
                id,
                "报表回归 " + id,
                mapper.convertValue(
                        config,
                        new com.fasterxml.jackson.core.type.TypeReference<
                                Map<String, Object>>() {}));
    }

    private String app(ApplicationReports.Config report, DataCenter.Definition... definitions) {
        var refs =
                Arrays.stream(definitions)
                        .map(
                                d -> {
                                    var v = objects.getVersion(d.objectId(), null);
                                    return new ApplicationCenter.ObjectReference(
                                            v.objectId(), v.versionNo(), v.checksum());
                                })
                        .toList();
        var a =
                apps.save(
                        new ApplicationCenter.Save(
                                null,
                                null,
                                fixture.prefix + "app" + serial++,
                                "报表验收",
                                null,
                                null,
                                new ApplicationCenter.Definition(
                                        refs, List.of(resource("report", "REPORT", report)))),
                        10001);
        grantApplicationObjects(a.application().id());
        apps.publish(new ApplicationCenter.Revision(a.application().id(), 0, "报表验收"), 10001);
        return a.application().id();
    }

    private ApplicationRecords.Row row(
            String app,
            DataCenter.Definition d,
            String name,
            String amount,
            String status,
            String date) {
        Map<String, Object> data = new LinkedHashMap<>();
        data.put(field(d, "name"), name);
        if (amount != null) data.put(field(d, "amount"), amount);
        if (status != null) data.put(field(d, "status"), status);
        if (date != null) data.put(field(d, "booked"), date);
        return records.save(
                        new ApplicationRecords.Save(app, d.objectId(), null, null, data, null),
                        10001)
                .record();
    }

    private ApplicationReports.Query query(String app) {
        return new ApplicationReports.Query(app, "report", null, null, null, null, null, 1, 20);
    }

    private com.richuang.os.common.dto.DynamicConditionDTO condition(
            String field, String op, Object value) {
        var item = new com.richuang.os.common.dto.DynamicConditionDTO.Item();
        item.setType("condition");
        item.setField(field);
        item.setOperator(op);
        item.setValue(value);
        var tree = new com.richuang.os.common.dto.DynamicConditionDTO();
        tree.setLogic(com.richuang.os.common.dto.DynamicConditionDTO.Logic.AND);
        tree.setItems(List.of(item));
        return tree;
    }

    private ApplicationReports.Config enhanced(
            DataCenter.Definition d,
            List<ApplicationReports.Metric> metrics,
            com.richuang.os.common.dto.DynamicConditionDTO fixed,
            boolean grouped) {
        return new ApplicationReports.Config(
                d.objectId(),
                grouped
                        ? List.of(new ApplicationReports.Dimension(field(d, "name"), null, "VALUE"))
                        : List.of(),
                metrics,
                Map.of(),
                List.of(field(d, "name"), field(d, "status"), field(d, "amount")),
                field(d, "booked"),
                "Asia/Shanghai",
                grouped ? "BAR" : "METRIC",
                null,
                false,
                30,
                null,
                fixed,
                new ApplicationReports.Chart("GROUPED", false, true, "TOP"));
    }

    @Test
    void conditionalMetricsRecomputeTotalsAndDrillWithMetricIdentity() {
        rollback(
                () -> {
                    var d = object(null, null);
                    var metrics =
                            List.of(
                                    new ApplicationReports.Metric(
                                            "total", "总数", "SUM", field(d, "amount")),
                                    new ApplicationReports.Metric(
                                            "used",
                                            "在用数",
                                            "SUM",
                                            field(d, "amount"),
                                            condition(field(d, "status"), "eq", "在用"),
                                            null,
                                            null),
                                    new ApplicationReports.Metric(
                                            "idle",
                                            "空闲数",
                                            "SUM",
                                            field(d, "amount"),
                                            condition(field(d, "status"), "eq", "空闲"),
                                            null,
                                            null),
                                    new ApplicationReports.Metric(
                                            "damaged",
                                            "损坏数",
                                            "SUM",
                                            field(d, "amount"),
                                            condition(field(d, "status"), "eq", "损坏"),
                                            null,
                                            null),
                                    new ApplicationReports.Metric(
                                            "rate",
                                            "在用率",
                                            "FORMULA",
                                            null,
                                            null,
                                            new ApplicationReports.Formula(
                                                    "DIVIDE", "used", "total"),
                                            new ApplicationReports.Format(null, 2, true, null)));
                    var config =
                            enhanced(d, metrics, condition(field(d, "amount"), "gte", "0"), true);
                    var app = app(config, d);
                    row(app, d, "研发部", "6", "在用", null);
                    row(app, d, "研发部", "3", "空闲", null);
                    row(app, d, "研发部", "1", "损坏", null);
                    row(app, d, "行政部", "2", "在用", null);
                    row(app, d, "行政部", "6", "空闲", null);
                    row(app, d, "排除负数", "-100", "在用", null);
                    var result = reports.query(query(app), 10001);
                    assertThat(result.recordCount()).isEqualTo(5);
                    assertThat(new java.math.BigDecimal(result.totals().get("total")))
                            .isEqualByComparingTo("18");
                    assertThat(result.totals().get("rate")).startsWith("0.444444");
                    var group =
                            result.groups().stream()
                                    .filter(g -> g.keys().getFirst().equals("行政部"))
                                    .findFirst()
                                    .orElseThrow();
                    assertThat(new java.math.BigDecimal(group.values().get("rate")))
                            .isEqualByComparingTo("0.25");
                    assertThat(new java.math.BigDecimal(group.values().get("damaged")))
                            .isEqualByComparingTo("0");
                    var detail =
                            reports.details(
                                    new ApplicationReports.Query(
                                            app,
                                            "report",
                                            null,
                                            null,
                                            null,
                                            null,
                                            List.of("研发部"),
                                            1,
                                            20,
                                            null,
                                            "used"),
                                    10001);
                    assertThat(detail.getTotal()).isEqualTo(1);
                    assertThat(detail.getList().getFirst().values().get(field(d, "status")))
                            .isEqualTo("在用");
                    assertThatThrownBy(
                                    () ->
                                            reports.details(
                                                    new ApplicationReports.Query(
                                                            app, "report", null, null, null, null,
                                                            null, 1, 20, null, "rate"),
                                                    10001))
                            .hasMessageContaining("引用指标");
                    assertThatThrownBy(
                                    () ->
                                            reports.details(
                                                    new ApplicationReports.Query(
                                                            app, "report", null, null, null, null,
                                                            null, 1, 20, null, "unknown"),
                                                    10001))
                            .hasMessageContaining("不存在");
                    var onlyIdle =
                            new ApplicationReports.Query(
                                    app,
                                    "report",
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    1,
                                    20,
                                    condition(field(d, "status"), "in", List.of("空闲", "损坏")),
                                    null);
                    var filtered = reports.query(onlyIdle, 10001);
                    assertThat(new java.math.BigDecimal(filtered.totals().get("total")))
                            .isEqualByComparingTo("10");
                    assertThat(new java.math.BigDecimal(filtered.totals().get("used")))
                            .isEqualByComparingTo("0");
                    assertThat(reports.export(query(app), 10001).totals())
                            .isEqualTo(result.totals());
                    var refs = apps.get(app).draft().objects();
                    assertThat(
                                    reports.preview(
                                                    new ApplicationReports.Preview(
                                                            app, refs, config, List.of()),
                                                    10001)
                                            .totals())
                            .isEqualTo(result.totals());
                    assertThat(
                                    reports.preview(
                                                    new ApplicationReports.Preview(
                                                            app, refs, config, List.of()),
                                                    10001)
                                            .canExport())
                            .isFalse();
                    var fields =
                            new HashSet<>(d.fields().stream().map(FieldDefinition::id).toList());
                    fields.remove(field(d, "status"));
                    sharing(app, d, grant(d, Set.of("READ", "EXPORT"), "ALL", fields));
                    assertThatThrownBy(() -> reports.query(query(app), 10001))
                            .hasMessageContaining("未授权字段");
                    assertThatThrownBy(
                                    () ->
                                            reports.preview(
                                                    new ApplicationReports.Preview(
                                                            app, refs, config, List.of()),
                                                    10001))
                            .hasMessageContaining("未授权字段");
                });
    }

    @Test
    void fieldCountsNullPredicatesAndEmptyRatiosRetainTheirSemantics() {
        rollback(
                () -> {
                    var d = object(null, null);
                    var metrics =
                            List.of(
                                    new ApplicationReports.Metric("all_rows", "记录", "COUNT", null),
                                    new ApplicationReports.Metric(
                                            "nonnull", "非空", "COUNT_FIELD", field(d, "amount")),
                                    new ApplicationReports.Metric(
                                            "unique_values",
                                            "去重",
                                            "COUNT_DISTINCT",
                                            field(d, "amount")),
                                    new ApplicationReports.Metric(
                                            "missing",
                                            "空值",
                                            "COUNT",
                                            null,
                                            condition(field(d, "amount"), "isNull", null),
                                            null,
                                            null),
                                    new ApplicationReports.Metric(
                                            "rate",
                                            "比例",
                                            "FORMULA",
                                            null,
                                            null,
                                            new ApplicationReports.Formula(
                                                    "DIVIDE", "nonnull", "all_rows"),
                                            null));
                    var app = app(enhanced(d, metrics, null, false), d);
                    row(app, d, "A", "0", null, null);
                    row(app, d, "A", "5", null, null);
                    row(app, d, "B", "5", null, null);
                    row(app, d, "C", null, null, null);
                    assertThat(reports.query(query(app), 10001).totals())
                            .containsEntry("all_rows", "4")
                            .containsEntry("nonnull", "3")
                            .containsEntry("unique_values", "2")
                            .containsEntry("missing", "1");
                    assertThat(
                                    reports.details(
                                                    new ApplicationReports.Query(
                                                            app, "report", null, null, null, null,
                                                            null, 1, 20, null, "nonnull"),
                                                    10001)
                                            .getTotal())
                            .isEqualTo(3);
                    var empty =
                            reports.query(
                                    new ApplicationReports.Query(
                                            app,
                                            "report",
                                            null,
                                            null,
                                            null,
                                            null,
                                            null,
                                            1,
                                            20,
                                            condition(
                                                    field(d, "amount"),
                                                    "between",
                                                    List.of("100", "200")),
                                            null),
                                    10001);
                    assertThat(empty.totals())
                            .containsEntry("all_rows", "0")
                            .containsEntry("unique_values", "0")
                            .containsEntry("rate", null);
                    var a = condition(field(d, "name"), "eq", "A");
                    var b = condition(field(d, "amount"), "isNull", null);
                    var or = new com.richuang.os.common.dto.DynamicConditionDTO();
                    or.setLogic(com.richuang.os.common.dto.DynamicConditionDTO.Logic.OR);
                    var nested = new com.richuang.os.common.dto.DynamicConditionDTO.Item();
                    nested.setType("group");
                    nested.setGroupLogic(a.getLogic());
                    nested.setGroupItems(a.getItems());
                    or.setItems(List.of(nested, b.getItems().getFirst()));
                    assertThat(
                                    reports.query(
                                                    new ApplicationReports.Query(
                                                            app, "report", null, null, null, null,
                                                            null, 1, 20, or, null),
                                                    10001)
                                            .recordCount())
                            .isEqualTo(3);
                    assertThatThrownBy(
                                    () ->
                                            reports.query(
                                                    new ApplicationReports.Query(
                                                            app,
                                                            "report",
                                                            null,
                                                            null,
                                                            null,
                                                            null,
                                                            null,
                                                            1,
                                                            20,
                                                            condition("unknown", "eq", "A"),
                                                            null),
                                                    10001))
                            .hasMessageContaining("开放的筛选字段");
                });
    }

    @Test
    void enhancedReportRejectsCyclesUnknownFieldsAndInvalidConditionsBeforePublishing() {
        rollback(
                () -> {
                    var d = object(null, null);
                    var validator = servicesContext.getBean(ApplicationReportValidator.class);
                    var objects = Map.of(d.objectId(), d);
                    var circular =
                            enhanced(
                                    d,
                                    List.of(
                                            new ApplicationReports.Metric(
                                                    "a",
                                                    "循环",
                                                    "FORMULA",
                                                    null,
                                                    null,
                                                    new ApplicationReports.Formula("ADD", "a", "a"),
                                                    null)),
                                    null,
                                    false);
                    assertThatThrownBy(() -> validator.normalize(circular, objects))
                            .hasMessageContaining("循环引用");
                    var missing =
                            enhanced(
                                    d,
                                    List.of(
                                            new ApplicationReports.Metric(
                                                    "a",
                                                    "失效",
                                                    "FORMULA",
                                                    null,
                                                    null,
                                                    new ApplicationReports.Formula(
                                                            "DIVIDE", "no_such_metric", "a"),
                                                    null)),
                                    null,
                                    false);
                    assertThatThrownBy(() -> validator.normalize(missing, objects))
                            .hasMessageContaining("不存在");
                    var base = List.of(new ApplicationReports.Metric("count", "计数", "COUNT", null));
                    assertThatThrownBy(
                                    () ->
                                            validator.normalize(
                                                    enhanced(
                                                            d,
                                                            base,
                                                            condition("unknown", "eq", "x"),
                                                            false),
                                                    objects))
                            .hasMessageContaining("不存在");
                    assertThatThrownBy(
                                    () ->
                                            validator.normalize(
                                                    enhanced(
                                                            d,
                                                            base,
                                                            condition(
                                                                    field(d, "status"),
                                                                    "eq) OR TRUE --",
                                                                    "x"),
                                                            false),
                                                    objects))
                            .isInstanceOf(RuntimeException.class);
                    assertThatThrownBy(
                                    () ->
                                            validator.normalize(
                                                    enhanced(
                                                            d,
                                                            base,
                                                            condition(
                                                                    field(d, "amount"),
                                                                    "between",
                                                                    List.of("1")),
                                                            false),
                                                    objects))
                            .hasMessageContaining("范围条件值");
                    assertThatThrownBy(
                                    () ->
                                            validator.normalize(
                                                    enhanced(
                                                            d,
                                                            base,
                                                            condition(
                                                                    field(d, "amount"),
                                                                    "eq",
                                                                    "not-a-number"),
                                                            false),
                                                    objects))
                            .hasMessageContaining("格式无效");
                });
    }

    private void sharing(
            String app, DataCenter.Definition d, ApplicationAuthorization.ObjectGrant grant) {
        var s = servicesContext.getBean(ObjectSharingService.class);
        int revision =
                s.forApplication(app).stream()
                        .filter(g -> g.objectId().equals(d.objectId()))
                        .findFirst()
                        .orElseThrow()
                        .revision();
        s.save(new ObjectSharing.Save(d.objectId(), app, revision, grant, "统计授权回归"), 10001);
    }

    private ApplicationAuthorization.ObjectGrant grant(
            DataCenter.Definition d, Set<String> actions, String scope, Set<String> fields) {
        return new ApplicationAuthorization.ObjectGrant(
                d.objectId(), actions, scope, fields, Set.of(), Set.of(), Set.of());
    }

    @org.junit.jupiter.params.ParameterizedTest
    @org.junit.jupiter.params.provider.ValueSource(
            strings = {"DEPARTMENT", "ORGANIZATION", "SELECT"})
    void singleDirectoryGroupsResolveNamesFilterDrillExportAndRespectPermissions(String type) {
        rollback(
                () -> {
                    var first = new com.richuang.os.module.system.dal.dataobject.dept.DeptDO();
                    first.setId(97101L);
                    first.setName("研发部");
                    first.setDeptCode("DEV_A");
                    first.setParentId(0L);
                    first.setStatus(0);
                    var second = new com.richuang.os.module.system.dal.dataobject.dept.DeptDO();
                    second.setId(97102L);
                    second.setName("市场部");
                    second.setDeptCode("DEV_B");
                    second.setParentId(0L);
                    second.setStatus(0);
                    var deptService =
                            servicesContext.getBean(
                                    com.richuang.os.module.system.service.dept.DeptService.class);
                    org.mockito.Mockito.when(
                                    deptService.getDeptList(
                                            org.mockito.ArgumentMatchers.any(
                                                    com.richuang.os.module.system.controller.admin
                                                            .dept.vo.dept.DeptListReqVO.class)))
                            .thenReturn(List.of(first, second));
                    var orgA =
                            new com.richuang.os.module.system.controller.admin.organization.vo
                                    .OrganizationTreeRespVO();
                    orgA.setId("97101");
                    orgA.setOrgName("研发部");
                    orgA.setOrgCode("ORG_A");
                    orgA.setOrgType(1);
                    orgA.setStatus(1);
                    var orgB =
                            new com.richuang.os.module.system.controller.admin.organization.vo
                                    .OrganizationTreeRespVO();
                    orgB.setId("97102");
                    orgB.setOrgName("市场部");
                    orgB.setOrgCode("ORG_B");
                    orgB.setOrgType(2);
                    orgB.setStatus(1);
                    org.mockito.Mockito.when(
                                    servicesContext
                                            .getBean(
                                                    com.richuang.os.module.system.service
                                                            .organization.OrganizationService.class)
                                            .getCurrentTenantTree(null, null))
                            .thenReturn(List.of(orgA, orgB));
                    var input = fixture.createRequest("directory_group");
                    var fields = new ArrayList<>(input.fields());
                    fields.add(fixture.field("department", "department", type, 1));
                    var option =
                            DataCenter.FieldOptions.defaults()
                                    .withSelection(
                                            new SelectionFields.Source(
                                                    "DIRECTORY",
                                                    "ORGANIZATION".equals(type)
                                                            ? type
                                                            : "DEPARTMENT",
                                                    null,
                                                    List.of(),
                                                    false,
                                                    List.of(),
                                                    "NONE"));
                    var design =
                            designs.save(
                                    new DataCenter.SaveDesign(
                                            new SaveObjectDraft(
                                                    null,
                                                    null,
                                                    input.objectCode(),
                                                    input.objectName(),
                                                    null,
                                                    input.tableName(),
                                                    input.titleFieldKey(),
                                                    fields,
                                                    List.of()),
                                            DataCenter.Settings.defaults(),
                                            Map.of("department", option),
                                            List.of(),
                                            List.of(),
                                            List.of()),
                                    10001);
                    var plan =
                            publisher.plan(
                                    new DataCenter.Revision(
                                            design.draft().id(),
                                            design.draft().lockVersion(),
                                            null),
                                    10001);
                    assertThat(plan.checks()).noneMatch(DataCenter.Check::blocking);
                    assertThat(
                                    publisher
                                            .execute(
                                                    new DataCenter.ExecutePlan(plan.id(), "目录分组回归"),
                                                    10001)
                                            .state())
                            .isEqualTo("SUCCEEDED");
                    var d = objects.getPublished(design.draft().id());
                    String department = field(d, "department");
                    var config =
                            new ApplicationReports.Config(
                                    d.objectId(),
                                    List.of(
                                            new ApplicationReports.Dimension(
                                                    department, null, "VALUE")),
                                    List.of(
                                            new ApplicationReports.Metric(
                                                    "count", "记录数", "COUNT", null)),
                                    Map.of(),
                                    List.of(department),
                                    null,
                                    "Asia/Shanghai",
                                    "TABLE",
                                    null,
                                    false,
                                    30,
                                    null);
                    String app = app(config, d);
                    var rowA =
                            records.save(
                                    new ApplicationRecords.Save(
                                            app,
                                            d.objectId(),
                                            null,
                                            null,
                                            Map.of(field(d, "name"), "A", department, "97101"),
                                            null),
                                    10001);
                    records.save(
                            new ApplicationRecords.Save(
                                    app,
                                    d.objectId(),
                                    null,
                                    null,
                                    Map.of(field(d, "name"), "B", department, "97101"),
                                    null),
                            10001);
                    records.save(
                            new ApplicationRecords.Save(
                                    app,
                                    d.objectId(),
                                    null,
                                    null,
                                    Map.of(field(d, "name"), "C", department, "97102"),
                                    null),
                            10001);
                    records.save(
                            new ApplicationRecords.Save(
                                    app,
                                    d.objectId(),
                                    null,
                                    null,
                                    Map.of(field(d, "name"), "空值"),
                                    null),
                            10001);
                    var query =
                            new ApplicationReports.Query(
                                    app, "report", null, null, null, null, null, 1, 10);
                    var result = reports.query(query, 10001);
                    assertThat(result.groups())
                            .extracting(g -> g.labels().getFirst())
                            .containsExactlyInAnyOrder("研发部", "市场部", "未填写");
                    var dev =
                            result.groups().stream()
                                    .filter(g -> "97101".equals(g.keys().getFirst()))
                                    .findFirst()
                                    .orElseThrow();
                    assertThat(dev.values().get("count")).isEqualTo("2");
                    assertThat(
                                    reports.details(
                                                    new ApplicationReports.Query(
                                                            app,
                                                            "report",
                                                            null,
                                                            null,
                                                            null,
                                                            null,
                                                            dev.keys(),
                                                            1,
                                                            10),
                                                    10001)
                                            .getList())
                            .extracting(ApplicationRecords.Row::id)
                            .contains(rowA.record().id())
                            .hasSize(2);
                    var filtered =
                            reports.query(
                                    new ApplicationReports.Query(
                                            app,
                                            "report",
                                            Map.of(department, "97102"),
                                            null,
                                            null,
                                            null,
                                            null,
                                            1,
                                            10),
                                    10001);
                    assertThat(filtered.recordCount()).isEqualTo(1);
                    assertThat(filtered.groups().getFirst().labels()).containsExactly("市场部");
                    assertThat(reports.export(query, 10001).groups()).isEqualTo(result.groups());
                    // 名称可重复或变更，分组与下钻身份仍使用目录 ID。
                    second.setName("研发部");
                    orgB.setOrgName("研发部");
                    assertThat(reports.query(query, 10001).groups())
                            .hasSize(3)
                            .filteredOn(g -> g.labels().getFirst().equals("研发部"))
                            .hasSize(2);
                    // 删除/撤回目录后保留原分组键，显示不可用提示，不丢弃历史计数。
                    org.mockito.Mockito.when(
                                    deptService.getDeptList(
                                            org.mockito.ArgumentMatchers.any(
                                                    com.richuang.os.module.system.controller.admin
                                                            .dept.vo.dept.DeptListReqVO.class)))
                            .thenReturn(List.of(first));
                    org.mockito.Mockito.when(
                                    servicesContext
                                            .getBean(
                                                    com.richuang.os.module.system.service
                                                            .organization.OrganizationService.class)
                                            .getCurrentTenantTree(null, null))
                            .thenReturn(List.of(orgA));
                    assertThat(reports.query(query, 10001).groups())
                            .filteredOn(g -> "97102".equals(g.keys().getFirst()))
                            .singleElement()
                            .satisfies(g -> assertThat(g.labels()).containsExactly("已失效或无权限的选项"));
                    sharing(
                            app,
                            d,
                            grant(d, Set.of("READ", "EXPORT"), "ALL", Set.of(field(d, "name"))));
                    assertThatThrownBy(() -> reports.query(query, 10001))
                            .hasMessageContaining("未授权字段");
                });
    }

    @Test
    void preciseMoneyNullGroupsTotalsAndDrillShareTheSameScope() {
        rollback(
                () -> {
                    var d = object(null, null);
                    String app =
                            app(
                                    config(
                                            d,
                                            List.of(
                                                    new ApplicationReports.Dimension(
                                                            field(d, "status"), null, "VALUE"))),
                                    d);
                    row(app, d, "甲", "9007199254740993.1000", "已付", "2026-09-01");
                    row(app, d, "乙", "0.2000", "已付", "2026-09-02");
                    row(app, d, "丙", null, null, "2026-08-02");
                    var result = reports.query(query(app), 10001);
                    assertThat(result.recordCount()).isEqualTo(3);
                    assertThat(result.totals().get("amount")).isEqualTo("9007199254740993.3000");
                    assertThat(result.totalGroups()).isEqualTo(2);
                    var group =
                            result.groups().stream()
                                    .filter(g -> g.keys().getFirst() == null)
                                    .findFirst()
                                    .orElseThrow();
                    assertThat(group.values().get("amount")).isEqualTo("0");
                    assertThat(group.values().get("average")).isNull();
                    var detail =
                            reports.details(
                                    new ApplicationReports.Query(
                                            app,
                                            "report",
                                            null,
                                            null,
                                            null,
                                            null,
                                            group.keys(),
                                            1,
                                            20),
                                    10001);
                    assertThat(detail.getTotal()).isEqualTo(1);
                    assertThat(detail.getList().getFirst().values().get(field(d, "name")))
                            .isEqualTo("丙");
                });
    }

    @Test
    void datesGroupsAndEmptyResultsHaveExplicitSemantics() {
        rollback(
                () -> {
                    var d = object(null, null);
                    String app =
                            app(
                                    config(
                                            d,
                                            List.of(
                                                    new ApplicationReports.Dimension(
                                                            field(d, "booked"), null, "MONTH"))),
                                    d);
                    row(app, d, "八月", "5", "a", "2026-08-31");
                    row(app, d, "九月", "10", "a", "2026-09-01");
                    row(app, d, "九月底", "20", "a", "2026-09-30");
                    var q =
                            new ApplicationReports.Query(
                                    app,
                                    "report",
                                    Map.of(field(d, "status"), "a"),
                                    "2026-09-01",
                                    "2026-09-30",
                                    null,
                                    List.of("2026-09"),
                                    1,
                                    20);
                    assertThat(reports.query(q, 10001).totals().get("amount")).isEqualTo("30.0000");
                    assertThat(reports.details(q, 10001).getTotal()).isEqualTo(2);
                    var empty =
                            reports.query(
                                    new ApplicationReports.Query(
                                            app,
                                            "report",
                                            Map.of(field(d, "status"), "missing"),
                                            null,
                                            null,
                                            null,
                                            null,
                                            1,
                                            20),
                                    10001);
                    assertThat(empty.groups()).isEmpty();
                    assertThat(empty.totals().get("amount")).isEqualTo("0");
                    assertThat(empty.totals().get("average")).isNull();
                });
    }

    @Test
    void sourceAndTargetPermissionRevocationBlockOldVersionsAndOwner() {
        rollback(
                () -> {
                    var company = object(null, null);
                    var flow = object(company, "REFERENCE");
                    var c =
                            config(
                                    flow,
                                    List.of(
                                            new ApplicationReports.Dimension(
                                                    field(company, "name"),
                                                    flow.relations().getFirst().id(),
                                                    "VALUE")));
                    String a = app(c, company, flow), b = app(c, company, flow);
                    row(a, flow, "流水", "100", "paid", "2026-09-01");
                    var full = NocodeIntegrationSupport.resolvedPermission(flow.objectId(), a);
                    var hidden = new HashSet<>(full.readFields());
                    hidden.remove(field(flow, "amount"));
                    sharing(a, flow, grant(flow, Set.of("READ"), "ALL", hidden));
                    assertThatThrownBy(() -> reports.query(query(a), 10001))
                            .hasMessageContaining("未授权字段");
                    assertThatThrownBy(() -> reports.details(query(a), 10001))
                            .hasMessageContaining("未授权字段");
                    assertThatThrownBy(() -> reports.export(query(a), 10001))
                            .hasMessageContaining("权限");
                    assertThat(reports.query(query(b), 10001).recordCount()).isEqualTo(1);
                    assertThat(
                                    servicesContext
                                            .getBean(ApplicationRuntimeService.class)
                                            .application(a, 10001)
                                            .definition()
                                            .resources())
                            .noneMatch(r -> r.kind().equals("REPORT"));
                    sharing(a, flow, full);
                    sharing(a, company, null);
                    assertThatThrownBy(() -> reports.query(query(a), 10001))
                            .hasMessageContaining("查看权限");
                });
    }

    @Test
    void memberOwnScopeAndReadOnlyExportCannotBeWidened() {
        rollback(
                () -> {
                    var d = object(null, null);
                    var app = app(config(d, List.of()), d);
                    row(app, d, "他人", "100", "x", "2026-09-01");
                    var own = row(app, d, "本人", "20", "x", "2026-09-01");
                    jdbc.update(
                            "UPDATE public.\""
                                    + d.tableName()
                                    + "\" SET creator='20002' WHERE id=?",
                            Long.parseLong(own.id()));
                    var fields =
                            d.fields().stream()
                                    .map(FieldDefinition::id)
                                    .collect(java.util.stream.Collectors.toSet());
                    var auth = servicesContext.getBean(ApplicationAuthorizationService.class);
                    auth.save(
                            new ApplicationAuthorization.Save(
                                    app,
                                    0,
                                    List.of(
                                            new ApplicationAuthorization.Member(
                                                    "USER",
                                                    "20002",
                                                    List.of(
                                                            grant(
                                                                    d,
                                                                    Set.of("READ"),
                                                                    "OWN",
                                                                    fields))))),
                            10001);
                    var result = reports.query(query(app), 20002);
                    assertThat(result.recordCount()).isEqualTo(1);
                    assertThat(result.totals().get("amount")).isEqualTo("20.0000");
                    assertThat(result.canExport()).isFalse();
                    assertThatThrownBy(() -> reports.export(query(app), 20002))
                            .hasMessageContaining("权限");
                    assertThat(reports.details(query(app), 20002).getTotal()).isEqualTo(1);
                });
    }

    @Test
    void singleRelationGroupingDoesNotMultiplyAndRespectsTargetRows() {
        rollback(
                () -> {
                    var company = object(null, null);
                    var flow = object(company, "REFERENCE");
                    var relation = flow.relations().getFirst();
                    var app =
                            app(
                                    config(
                                            flow,
                                            List.of(
                                                    new ApplicationReports.Dimension(
                                                            field(company, "name"),
                                                            relation.id(),
                                                            "VALUE"))),
                                    company,
                                    flow);
                    var a = row(app, company, "公司甲", null, null, null);
                    var b = row(app, company, "公司乙", null, null, null);
                    for (int i = 0; i < 3; i++) {
                        var row = row(app, flow, "流水" + i, "10", null, "2026-09-01");
                        records.save(
                                new ApplicationRecords.Save(
                                        app,
                                        flow.objectId(),
                                        row.id(),
                                        row.revision(),
                                        Map.of(relation.fieldId(), i < 2 ? a.id() : b.id()),
                                        null),
                                10001);
                    }
                    var result = reports.query(query(app), 10001);
                    assertThat(result.recordCount()).isEqualTo(3);
                    assertThat(result.groups()).hasSize(2);
                    assertThat(result.totals().get("amount")).isEqualTo("30.0000");
                    jdbc.update(
                            "UPDATE public.\""
                                    + company.tableName()
                                    + "\" SET creator='20002' WHERE id=?",
                            Long.parseLong(b.id()));
                    var full = NocodeIntegrationSupport.resolvedPermission(company.objectId(), app);
                    sharing(
                            app,
                            company,
                            grant(company, Set.of("READ", "EXPORT"), "OWN", full.readFields()));
                    assertThat(reports.query(query(app), 10001).recordCount()).isEqualTo(2);
                    assertThat(reports.details(query(app), 10001).getTotal()).isEqualTo(2);
                });
    }

    @Test
    void fixedConditionsAndTopGroupsDoNotAlterGrandTotals() {
        rollback(
                () -> {
                    var d = object(null, null);
                    var original =
                            config(
                                    d,
                                    List.of(
                                            new ApplicationReports.Dimension(
                                                    field(d, "name"), null, "VALUE")));
                    var c =
                            new ApplicationReports.Config(
                                    d.objectId(),
                                    original.dimensions(),
                                    original.metrics(),
                                    Map.of(field(d, "status"), "paid"),
                                    original.filterFieldIds(),
                                    original.dateFieldId(),
                                    original.timeZone(),
                                    "TABLE",
                                    "amount",
                                    true,
                                    1,
                                    null);
                    String app = app(c, d);
                    row(app, d, "a", "10", "paid", null);
                    row(app, d, "b", "20", "paid", null);
                    row(app, d, "c", "100", "unpaid", null);
                    var r = reports.query(query(app), 10001);
                    assertThat(r.groups()).hasSize(1);
                    assertThat(r.totalGroups()).isEqualTo(2);
                    assertThat(r.recordCount()).isEqualTo(2);
                    assertThat(r.totals().get("amount")).isEqualTo("30.0000");
                    assertThat(r.groups().getFirst().keys()).containsExactly("b");
                    assertThatThrownBy(
                                    () ->
                                            reports.query(
                                                    new ApplicationReports.Query(
                                                            app,
                                                            "report",
                                                            Map.of(field(d, "status"), "unpaid"),
                                                            null,
                                                            null,
                                                            null,
                                                            null,
                                                            1,
                                                            20),
                                                    10001))
                            .hasMessageContaining("固定");
                    assertThatThrownBy(
                                    () ->
                                            reports.query(
                                                    new ApplicationReports.Query(
                                                            app,
                                                            "report",
                                                            Map.of("name;drop table", "x"),
                                                            null,
                                                            null,
                                                            null,
                                                            null,
                                                            1,
                                                            20),
                                                    10001))
                            .hasMessageContaining("筛选");
                    assertThat(
                                    reports.query(
                                                    new ApplicationReports.Query(
                                                            app,
                                                            "report",
                                                            Map.of(field(d, "status"), "paid"),
                                                            null,
                                                            null,
                                                            null,
                                                            null,
                                                            1,
                                                            20),
                                                    10001)
                                            .recordCount())
                            .isEqualTo(2);
                });
    }

    @Test
    void twoHopCompanyGroupingAndFiltersFollowAccountOwnership() {
        rollback(
                () -> {
                    var company = object(null, null);
                    var account = object(company, "REFERENCE");
                    var flow = object(account, "REFERENCE");
                    String first = flow.relations().getFirst().id(),
                            second = account.relations().getFirst().id();
                    var original =
                            config(
                                    flow,
                                    List.of(
                                            new ApplicationReports.Dimension(
                                                    field(company, "name"),
                                                    first + "/" + second,
                                                    "VALUE")));
                    String companyFilter = first + ":" + account.relations().getFirst().fieldId();
                    var c =
                            new ApplicationReports.Config(
                                    flow.objectId(),
                                    original.dimensions(),
                                    original.metrics(),
                                    Map.of(),
                                    List.of(companyFilter),
                                    original.dateFieldId(),
                                    original.timeZone(),
                                    original.display(),
                                    null,
                                    false,
                                    30,
                                    null);
                    String app = app(c, company, account, flow);
                    var a = row(app, company, "公司甲", null, null, null);
                    var b = row(app, company, "公司乙", null, null, null);
                    for (int i = 0; i < 3; i++) {
                        var bank = row(app, account, "账户" + i, null, null, null);
                        records.save(
                                new ApplicationRecords.Save(
                                        app,
                                        account.objectId(),
                                        bank.id(),
                                        bank.revision(),
                                        Map.of(
                                                account.relations().getFirst().fieldId(),
                                                i < 2 ? a.id() : b.id()),
                                        null),
                                10001);
                        var bill = row(app, flow, "流水" + i, "10", null, "2026-09-01");
                        records.save(
                                new ApplicationRecords.Save(
                                        app,
                                        flow.objectId(),
                                        bill.id(),
                                        bill.revision(),
                                        Map.of(flow.relations().getFirst().fieldId(), bank.id()),
                                        null),
                                10001);
                    }
                    var all = reports.query(query(app), 10001);
                    assertThat(all.totalGroups()).isEqualTo(2);
                    assertThat(all.recordCount()).isEqualTo(3);
                    var q =
                            new ApplicationReports.Query(
                                    app,
                                    "report",
                                    Map.of(companyFilter, a.id()),
                                    null,
                                    null,
                                    null,
                                    null,
                                    1,
                                    20);
                    assertThat(reports.query(q, 10001).totals().get("amount")).isEqualTo("20.0000");
                    assertThat(reports.details(q, 10001).getTotal()).isEqualTo(2);
                    assertThat(reports.export(q, 10001).recordCount()).isEqualTo(2);
                    var full = NocodeIntegrationSupport.resolvedPermission(account.objectId(), app);
                    var hidden = new HashSet<>(full.readFields());
                    hidden.remove(account.relations().getFirst().fieldId());
                    sharing(app, account, grant(account, Set.of("READ", "EXPORT"), "ALL", hidden));
                    assertThatThrownBy(() -> reports.query(q, 10001)).hasMessageContaining("未授权字段");
                });
    }

    @Test
    void manyToManyContextUsesExistsAndCannotBypassCurrentRecordOrRelationPermissions() {
        rollback(
                () -> {
                    var company = object(null, null);
                    var fact = object(company, "MANY_TO_MANY");
                    String app = app(config(fact, List.of()), company, fact);
                    var a = row(app, company, "甲公司", null, null, null);
                    var b = row(app, company, "乙公司", null, null, null);
                    var one = row(app, fact, "同时关联两家公司", "10", null, null);
                    var two = row(app, fact, "仅关联乙公司", "20", null, null);
                    var relation = fact.relations().getFirst();
                    records.save(
                            new ApplicationRecords.Save(
                                    app,
                                    fact.objectId(),
                                    one.id(),
                                    one.revision(),
                                    Map.of(),
                                    null,
                                    Map.of(relation.id(), List.of(a.id(), b.id()))),
                            10001);
                    records.save(
                            new ApplicationRecords.Save(
                                    app,
                                    fact.objectId(),
                                    two.id(),
                                    two.revision(),
                                    Map.of(),
                                    null,
                                    Map.of(relation.id(), List.of(b.id()))),
                            10001);
                    var node =
                            new ApplicationUi.Node(
                                    "scoped_report",
                                    "REPORT",
                                    null,
                                    "report",
                                    "关联统计",
                                    null,
                                    List.of(),
                                    new ApplicationUi.RelationBinding(relation.id(), "INCOMING"),
                                    null);
                    var page = new ApplicationUi.Page(List.of(node), company.objectId(), 2);
                    var before = apps.get(app);
                    var resources = new ArrayList<>(before.draft().resources());
                    resources.add(resource("scope_page", "PAGE", page));
                    var saved =
                            apps.save(
                                    new ApplicationCenter.Save(
                                            app,
                                            before.application().revision(),
                                            before.application().code(),
                                            before.application().name(),
                                            null,
                                            null,
                                            new ApplicationCenter.Definition(
                                                    before.draft().objects(), resources)),
                                    10001);
                    apps.publish(
                            new ApplicationCenter.Revision(
                                    app, saved.application().revision(), "关联统计测试"),
                            10001);
                    var q =
                            new ApplicationReports.Query(
                                    app,
                                    "report",
                                    null,
                                    null,
                                    null,
                                    new ApplicationRecords.Context(
                                            "scope_page", "scoped_report", a.id()),
                                    null,
                                    1,
                                    20);
                    assertThat(reports.query(q, 10001).recordCount()).isEqualTo(1);
                    assertThat(reports.query(q, 10001).totals().get("amount")).isEqualTo("10.0000");
                    assertThat(reports.details(q, 10001).getTotal()).isEqualTo(1);
                    assertThatThrownBy(
                                    () ->
                                            records.save(
                                                    new ApplicationRecords.Save(
                                                            app,
                                                            fact.objectId(),
                                                            null,
                                                            null,
                                                            Map.of(field(fact, "name"), "不得从报表创建"),
                                                            null,
                                                            null,
                                                            q.context()),
                                                    10001))
                            .hasMessageContaining("关联区块不存在");
                    var full = NocodeIntegrationSupport.resolvedPermission(fact.objectId(), app);
                    sharing(
                            app,
                            fact,
                            grant(fact, Set.of("READ", "EXPORT"), "ALL", full.readFields()));
                    assertThatThrownBy(() -> reports.query(q, 10001)).hasMessageContaining("关联关系");
                });
    }

    @Test
    void zonedTimestampUsesConfiguredBusinessDayAndDrillAgrees() {
        rollback(
                () -> {
                    var d = object(null, null, true);
                    var original =
                            config(
                                    d,
                                    List.of(
                                            new ApplicationReports.Dimension(
                                                    field(d, "booked"), null, "DAY")));
                    String app = app(original, d);
                    row(app, d, "北京时间九月一日", "10", null, "2026-08-31T17:30:00Z");
                    row(app, d, "北京时间八月三十一日", "20", null, "2026-08-31T15:30:00Z");
                    var q =
                            new ApplicationReports.Query(
                                    app,
                                    "report",
                                    null,
                                    "2026-09-01",
                                    "2026-09-01",
                                    null,
                                    List.of("2026-09-01"),
                                    1,
                                    20);
                    var result = reports.query(q, 10001);
                    assertThat(result.groups().getFirst().keys()).containsExactly("2026-09-01");
                    assertThat(result.totals().get("amount")).isEqualTo("10.0000");
                    assertThat(reports.details(q, 10001).getTotal()).isEqualTo(1);
                });
    }

    @Test
    void integerReferenceFiltersRejectDifferentTargetsAndRestoreKeepsReportConfiguration() {
        rollback(
                () -> {
                    var company = object(null, null);
                    var department = object(null, null);
                    var source = object(company, "REFERENCE");
                    var other = object(department, "REFERENCE");
                    var sourceField = source.relations().getFirst().fieldId();
                    var otherField = other.relations().getFirst().fieldId();
                    var base = config(source, List.of());
                    var report =
                            new ApplicationReports.Config(
                                    source.objectId(),
                                    base.dimensions(),
                                    base.metrics(),
                                    Map.of(),
                                    List.of(sourceField),
                                    base.dateFieldId(),
                                    base.timeZone(),
                                    base.display(),
                                    null,
                                    false,
                                    20,
                                    null);
                    String id = app(report, source, company, other, department);
                    row(id, source, "保留的业务记录", "10", null, null);
                    var detail = apps.get(id);
                    var node =
                            new ApplicationUi.Node(
                                    "report_node", "REPORT", null, "report", null, null, List.of());
                    var filter =
                            new ApplicationReports.Filter(
                                    "company",
                                    "公司",
                                    source.objectId(),
                                    sourceField,
                                    false,
                                    Map.of("report", sourceField));
                    var page =
                            resource(
                                    "page",
                                    "PAGE",
                                    new ApplicationUi.Page(
                                            List.of(node), null, 2, List.of(filter)));
                    var list = List.of(resource("report", "REPORT", report), page);
                    var saved =
                            apps.save(
                                    new ApplicationCenter.Save(
                                            id,
                                            detail.application().revision(),
                                            detail.application().code(),
                                            detail.application().name(),
                                            null,
                                            null,
                                            new ApplicationCenter.Definition(
                                                    detail.draft().objects(), list)),
                                    10001);
                    apps.publish(
                            new ApplicationCenter.Revision(
                                    id, saved.application().revision(), "含统一筛选的 V2"),
                            10001);
                    var wrong =
                            new ApplicationReports.Filter(
                                    "company",
                                    "错误映射",
                                    other.objectId(),
                                    otherField,
                                    false,
                                    Map.of("report", sourceField));
                    assertThatThrownBy(
                                    () ->
                                            servicesContext
                                                    .getBean(ApplicationResourceValidator.class)
                                                    .normalize(
                                                            detail.draft().objects(),
                                                            List.of(
                                                                    resource(
                                                                            "report", "REPORT",
                                                                            report),
                                                                    resource(
                                                                            "page",
                                                                            "PAGE",
                                                                            new ApplicationUi.Page(
                                                                                    List.of(node),
                                                                                    null,
                                                                                    2,
                                                                                    List.of(
                                                                                            wrong))))))
                            .hasMessageContaining("同一对象");
                    var current = apps.get(id);
                    var restored =
                            apps.restore(
                                    new ApplicationCenter.Restore(
                                            id, current.application().revision(), 1, "恢复不含页面的版本"),
                                    10001);
                    assertThat(apps.published(id).definition().resources()).hasSize(1);
                    var restoredAgain =
                            apps.restore(
                                    new ApplicationCenter.Restore(
                                            id, restored.application().revision(), 2, "恢复统计页面与联动"),
                                    10001);
                    assertThat(restoredAgain.application().publishedVersion()).isEqualTo(4);
                    var recovered =
                            apps.published(id).definition().resources().stream()
                                    .filter(r -> r.id().equals("page"))
                                    .findFirst()
                                    .orElseThrow();
                    assertThat(
                                    mapper.convertValue(
                                                    recovered.config(), ApplicationUi.Page.class)
                                            .filters())
                            .containsExactly(filter);
                    var q =
                            new ApplicationReports.Query(
                                    id, "report", null, null, null, null, null, 1, 20);
                    assertThat(reports.query(q, 10001).totals().get("amount")).isEqualTo("10.0000");
                    assertThat(reports.details(q, 10001).getTotal()).isEqualTo(1);
                });
    }

    @Test
    void invalidFieldsExecutableConfigAndBrokenResourcesAreRejectedAtSave() {
        rollback(
                () -> {
                    var d = object(null, null);
                    var original = config(d, List.of());
                    var broken =
                            new ApplicationReports.Config(
                                    d.objectId(),
                                    List.of(
                                            new ApplicationReports.Dimension(
                                                    "amount;delete", null, "VALUE")),
                                    original.metrics(),
                                    Map.of(),
                                    List.of(),
                                    null,
                                    "Asia/Shanghai",
                                    "TABLE",
                                    null,
                                    false,
                                    20,
                                    null);
                    assertThatThrownBy(() -> app(broken, d)).hasMessageContaining("统计字段");
                    var wrong =
                            new ApplicationReports.Config(
                                    d.objectId(),
                                    List.of(),
                                    original.metrics(),
                                    Map.of(),
                                    List.of(),
                                    null,
                                    "bogus/timezone",
                                    "METRIC",
                                    null,
                                    false,
                                    20,
                                    null);
                    assertThatThrownBy(() -> app(wrong, d)).hasMessageContaining("时区");
                    var app = app(original, d);
                    assertThatThrownBy(
                                    () ->
                                            reports.query(
                                                    new ApplicationReports.Query(
                                                            app,
                                                            "not_published",
                                                            null,
                                                            null,
                                                            null,
                                                            null,
                                                            null,
                                                            1,
                                                            20),
                                                    10001))
                            .hasMessageContaining("不存在");
                    assertThatThrownBy(
                                    () ->
                                            reports.query(
                                                    new ApplicationReports.Query(
                                                            app,
                                                            "report",
                                                            null,
                                                            "2026-10-01",
                                                            "2026-09-01",
                                                            null,
                                                            null,
                                                            1,
                                                            20),
                                                    10001))
                            .hasMessageContaining("开始日期");
                });
    }
}
