package com.richuang.os.nocode.runtime.dal.query;

import java.util.List;
import java.util.Map;

/** 仅供服务编译的 MyBatis 参数。表列名称来自固定对象版本和数据库目录，绝不直接接收 HTTP DTO。 */
public record RecordStatement(
        String schema,
        String table,
        String keyColumn,
        Map<String, String> fields,
        List<String> textFields,
        List<String> numericFields,
        boolean deletedColumn,
        String id,
        String parentColumn,
        String parentId,
        String creator,
        String search,
        List<String> filterColumns,
        String filters,
        String sortColumn,
        boolean descending,
        int limit,
        int offset,
        List<String> columns,
        String payload,
        String actor,
        boolean lock,
        RelationScope relationScope,
        com.baomidou.mybatisplus.core.conditions.query.QueryWrapper<Object> dynamicQuery,
        ReportRootScope dashboardScope) {
    public RecordStatement(
            String schema,
            String table,
            String keyColumn,
            Map<String, String> fields,
            List<String> textFields,
            List<String> numericFields,
            boolean deletedColumn,
            String id,
            String parentColumn,
            String parentId,
            String creator,
            String search,
            List<String> filterColumns,
            String filters,
            String sortColumn,
            boolean descending,
            int limit,
            int offset,
            List<String> columns,
            String payload,
            String actor,
            boolean lock,
            RelationScope relationScope,
            com.baomidou.mybatisplus.core.conditions.query.QueryWrapper<Object> dynamicQuery) {
        this(
                schema,
                table,
                keyColumn,
                fields,
                textFields,
                numericFields,
                deletedColumn,
                id,
                parentColumn,
                parentId,
                creator,
                search,
                filterColumns,
                filters,
                sortColumn,
                descending,
                limit,
                offset,
                columns,
                payload,
                actor,
                lock,
                relationScope,
                dynamicQuery,
                null);
    }

    public RecordStatement(
            String schema,
            String table,
            String keyColumn,
            Map<String, String> fields,
            List<String> textFields,
            List<String> numericFields,
            boolean deletedColumn,
            String id,
            String parentColumn,
            String parentId,
            String creator,
            String search,
            List<String> filterColumns,
            String filters,
            String sortColumn,
            boolean descending,
            int limit,
            int offset,
            List<String> columns,
            String payload,
            String actor,
            boolean lock,
            RelationScope relationScope) {
        this(
                schema,
                table,
                keyColumn,
                fields,
                textFields,
                numericFields,
                deletedColumn,
                id,
                parentColumn,
                parentId,
                creator,
                search,
                filterColumns,
                filters,
                sortColumn,
                descending,
                limit,
                offset,
                columns,
                payload,
                actor,
                lock,
                relationScope,
                null);
    }

    public RecordStatement conditions(
            com.baomidou.mybatisplus.core.conditions.query.QueryWrapper<Object> query) {
        return new RecordStatement(
                schema,
                table,
                keyColumn,
                fields,
                textFields,
                numericFields,
                deletedColumn,
                id,
                parentColumn,
                parentId,
                creator,
                search,
                filterColumns,
                filters,
                sortColumn,
                descending,
                limit,
                offset,
                columns,
                payload,
                actor,
                lock,
                relationScope,
                query,
                dashboardScope);
    }

    /** 内部完整计算分页；调用方先计数，超预算拒绝而不是截断计算。 */
    public RecordStatement page(int size, int start) {
        return new RecordStatement(
                schema,
                table,
                keyColumn,
                fields,
                textFields,
                numericFields,
                deletedColumn,
                id,
                parentColumn,
                parentId,
                creator,
                search,
                filterColumns,
                filters,
                sortColumn,
                descending,
                size,
                start,
                columns,
                payload,
                actor,
                lock,
                relationScope,
                dynamicQuery,
                dashboardScope);
    }

    public RecordStatement(
            String schema,
            String table,
            String keyColumn,
            Map<String, String> fields,
            List<String> textFields,
            List<String> numericFields,
            boolean deletedColumn,
            String id,
            String parentColumn,
            String parentId,
            String creator,
            String search,
            List<String> filterColumns,
            String filters,
            String sortColumn,
            boolean descending,
            int limit,
            int offset,
            List<String> columns,
            String payload,
            String actor,
            boolean lock) {
        this(
                schema,
                table,
                keyColumn,
                fields,
                textFields,
                numericFields,
                deletedColumn,
                id,
                parentColumn,
                parentId,
                creator,
                search,
                filterColumns,
                filters,
                sortColumn,
                descending,
                limit,
                offset,
                columns,
                payload,
                actor,
                lock,
                null);
    }

    public RecordStatement scope(
            String fixedId, String column, String value, RelationScope relation) {
        String effectiveId =
                fixedId == null ? id : id != null && !id.equals(fixedId) ? "" : fixedId;
        return new RecordStatement(
                schema,
                table,
                keyColumn,
                fields,
                textFields,
                numericFields,
                deletedColumn,
                effectiveId,
                column,
                value,
                creator,
                search,
                filterColumns,
                filters,
                sortColumn,
                descending,
                limit,
                offset,
                columns,
                payload,
                actor,
                lock,
                relation,
                dynamicQuery,
                dashboardScope);
    }

    /** 完整 SQL 范围与分页、关系上下文和动态条件一起保留，不先读取主键集合。 */
    public RecordStatement dashboardScope(ReportRootScope scope) {
        return new RecordStatement(
                schema,
                table,
                keyColumn,
                fields,
                textFields,
                numericFields,
                deletedColumn,
                id,
                parentColumn,
                parentId,
                creator,
                search,
                filterColumns,
                filters,
                sortColumn,
                descending,
                limit,
                offset,
                columns,
                payload,
                actor,
                lock,
                relationScope,
                dynamicQuery,
                scope);
    }
}
