-- 授权即时生效，不进入可回退的应用发布快照。
CREATE TABLE public.nocode_application_access (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL UNIQUE REFERENCES public.nocode_application(id),
    lock_version integer NOT NULL DEFAULT 0,
    policy_json jsonb NOT NULL DEFAULT '[]'::jsonb CHECK(jsonb_typeof(policy_json)='array'),
    creator varchar(64) DEFAULT '', create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '', update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1))
);
COMMENT ON TABLE public.nocode_application_access IS '应用成员、对象操作、记录范围和字段授权；身份复用系统用户与角色';
