CREATE TABLE public.nocode_record_process (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES public.nocode_application(id),
    application_version integer NOT NULL,
    object_id bigint NOT NULL REFERENCES public.nocode_object(id),
    object_version integer NOT NULL,
    record_id varchar(500) NOT NULL,
    action_id varchar(80) NOT NULL,
    name varchar(160) NOT NULL,
    business_key varchar(80) NOT NULL UNIQUE,
    process_definition_id varchar(128) NOT NULL,
    process_definition_key varchar(128) NOT NULL,
    process_instance_id varchar(128) UNIQUE,
    status varchar(20) NOT NULL CHECK(status IN ('RUNNING','APPROVED','REJECTED','CANCELED')),
    end_time timestamp(6),
    creator varchar(64) DEFAULT '', create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '', update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1))
);
CREATE UNIQUE INDEX nocode_record_process_one_active ON public.nocode_record_process(object_id,record_id) WHERE status='RUNNING' AND deleted=0;
CREATE INDEX nocode_record_process_application ON public.nocode_record_process(application_id,status) WHERE deleted=0;
COMMENT ON TABLE public.nocode_record_process IS '已有业务记录与底座 BPM 流程实例关联；审批期间保护同一全局记录';
