-- 对象授予应用的实时上限；缺少记录或 grant_json=null 都拒绝业务访问。
CREATE TABLE public.nocode_object_application_grant (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id bigint NOT NULL REFERENCES public.nocode_object(id),
    application_id bigint NOT NULL REFERENCES public.nocode_application(id),
    lock_version integer NOT NULL DEFAULT 0,
    grant_json jsonb NOT NULL CHECK(jsonb_typeof(grant_json) IN ('object','null')),
    reason varchar(1000) NOT NULL,
    creator varchar(64) DEFAULT '', create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '', update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1)),
    UNIQUE(object_id,application_id)
);
CREATE INDEX nocode_object_application_grant_app ON public.nocode_object_application_grant(application_id);
COMMENT ON TABLE public.nocode_object_application_grant IS '对象对应用的授权上限；应用内部授权和创建人均不得超出；独立于发布快照';

CREATE TABLE public.nocode_object_application_grant_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id bigint NOT NULL REFERENCES public.nocode_object(id),
    application_id bigint NOT NULL REFERENCES public.nocode_application(id),
    lock_version integer NOT NULL,
    grant_json jsonb NOT NULL,
    reason varchar(1000) NOT NULL,
    creator varchar(64) DEFAULT '', create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '', update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1)),
    UNIQUE(object_id,application_id,lock_version)
);
COMMENT ON TABLE public.nocode_object_application_grant_log IS '对象共享授权变更审计；包括迁移固化、收紧和撤销';

-- 一次性兼容已有受信搭建模式。仅固化迁移时已有草稿/当前发布引用及其字段，不给未来应用、字段或关系自动授权。
WITH refs AS (
    SELECT a.id AS app_id, r->>'objectId' AS object_id, (r->>'versionNo')::integer AS version_no
    FROM public.nocode_application a CROSS JOIN LATERAL jsonb_array_elements(a.design_json->'objects') r WHERE a.deleted=0
    UNION
    SELECT a.id, r->>'objectId', (r->>'versionNo')::integer
    FROM public.nocode_application a JOIN public.nocode_application_version v ON v.application_id=a.id AND v.version_no=a.published_version
    CROSS JOIN LATERAL jsonb_array_elements(v.definition_json->'definition'->'objects') r WHERE a.deleted=0 AND v.deleted=0
), schemas AS (
    SELECT r.app_id,r.object_id::bigint AS object_id,v.schema_json AS d FROM refs r
    JOIN public.nocode_object_version v ON v.object_id=r.object_id::bigint AND v.version_no=r.version_no AND v.state='PUBLISHED' AND v.deleted=0
), pairs AS (
    SELECT DISTINCT app_id,object_id FROM schemas
), permissions AS (
    SELECT p.*, jsonb_build_object(
        'objectId',p.object_id::text,'scope','ALL','actions',jsonb_build_array('READ','CREATE','UPDATE','DELETE','IMPORT','EXPORT','START_PROCESS'),
        'readFields',COALESCE((SELECT jsonb_agg(DISTINCT f->>'id') FROM schemas s CROSS JOIN LATERAL jsonb_array_elements(s.d->'fields') f WHERE s.app_id=p.app_id AND s.object_id=p.object_id),'[]'::jsonb),
        'readDetails',COALESCE((SELECT jsonb_agg(DISTINCT t->>'id') FROM schemas s CROSS JOIN LATERAL jsonb_array_elements(s.d->'details') t WHERE s.app_id=p.app_id AND s.object_id=p.object_id AND t->>'state'='ACTIVE'),'[]'::jsonb),
        'readRelations',COALESCE((SELECT jsonb_agg(DISTINCT r->>'id') FROM schemas s CROSS JOIN LATERAL jsonb_array_elements(s.d->'relations') r WHERE s.app_id=p.app_id AND s.object_id=p.object_id AND r->>'kind'='MANY_TO_MANY'),'[]'::jsonb)
    ) AS permission_json FROM pairs p
)
INSERT INTO public.nocode_object_application_grant(object_id,application_id,lock_version,grant_json,reason,creator,updater)
SELECT object_id,app_id,1,permission_json || jsonb_build_object('writeFields',permission_json->'readFields','writeDetails',permission_json->'readDetails','writeRelations',permission_json->'readRelations'),
    'V011 兼容迁移：固化原有应用范围，需由数据管理员审查；未来成员仍受应用内部授权限制','nocode-migration','nocode-migration'
FROM permissions;

INSERT INTO public.nocode_object_application_grant_log(object_id,application_id,lock_version,grant_json,reason,creator,updater)
SELECT object_id,application_id,lock_version,grant_json,reason,creator,updater FROM public.nocode_object_application_grant;

-- 使用底座按钮权限。普通应用创建/管理权限不包含对象共享授权权限；不自动授予业务团队角色。
INSERT INTO public.system_menu(id,name,permission,type,sort,parent_id,path,icon,status,visible,keep_alive,always_show,creator,updater,create_time,update_time,deleted)
SELECT nextval('public.system_menu_seq'),'管理对象共享授权','nocode:object:share',3,40,id,'','',0,true,false,false,'nocode-migration','nocode-migration',now(),now(),0
FROM public.system_menu WHERE permission='nocode:object:query' AND type=2 AND deleted=0
AND NOT EXISTS(SELECT 1 FROM public.system_menu WHERE permission='nocode:object:share' AND deleted=0);
