-- 平台网盘基础结构。前置 V031；为 infra_file 增加受保护标识，并建立 drive 空间、节点、授权、分享与用户标记六张表。
-- 不改动既有文件记录与配置：新列默认 false，既有文件仍可按通用接口读取。
-- 校验：受保护文件对通用文件接口（按路径、按编号）不可读取；空间隔离、目录防循环移动、回收站与物理删除分离按专项集成测试核对。
ALTER TABLE public.infra_file
    ADD COLUMN protected_flag boolean NOT NULL DEFAULT false;
CREATE INDEX infra_file_protected_idx
    ON public.infra_file(config_id, path) WHERE protected_flag AND deleted = 0;
COMMENT ON COLUMN public.infra_file.protected_flag IS '受保护文件：内容只能由业务模块鉴权后读取，通用文件接口拒绝访问';

CREATE TABLE public.drive_space (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(128) NOT NULL,
    type varchar(16) NOT NULL,
    owner_id bigint NOT NULL,
    owner_dept_id bigint,
    quota_bytes bigint NOT NULL DEFAULT 0,
    used_bytes bigint NOT NULL DEFAULT 0,
    status smallint NOT NULL DEFAULT 0,
    creator varchar(64) DEFAULT '', create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '', update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1))
);
CREATE UNIQUE INDEX drive_space_personal_uk
    ON public.drive_space(owner_id) WHERE type='PERSONAL' AND deleted=0;
CREATE INDEX drive_space_type_idx
    ON public.drive_space(type,status) WHERE deleted=0;
COMMENT ON TABLE public.drive_space IS '网盘空间：个人空间按用户唯一建立，团队空间按部门或责任人建立';
COMMENT ON COLUMN public.drive_space.type IS '空间类型：PERSONAL 个人空间、TEAM 团队空间';
COMMENT ON COLUMN public.drive_space.owner_id IS '归属主体用户编号：个人空间的所属用户，团队空间的责任人';
COMMENT ON COLUMN public.drive_space.owner_dept_id IS '归属部门编号：团队空间所属部门，个人空间为空';
COMMENT ON COLUMN public.drive_space.quota_bytes IS '容量配额（字节），0 表示不限制；V1 只记录不拦截上传';
COMMENT ON COLUMN public.drive_space.used_bytes IS '已用容量（字节），按未进回收站的文件节点累计，回收站内容不占容量';
COMMENT ON COLUMN public.drive_space.status IS '空间状态，枚举 CommonStatusEnum：0 开启、1 关闭；关闭后不再提供内容访问';

CREATE TABLE public.drive_entry (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id bigint NOT NULL REFERENCES public.drive_space(id),
    parent_id bigint NOT NULL DEFAULT 0,
    name varchar(255) NOT NULL,
    type varchar(16) NOT NULL,
    file_id bigint,
    size bigint NOT NULL DEFAULT 0,
    mime_type varchar(128),
    inherit_parent boolean NOT NULL DEFAULT true,
    trash_state varchar(16) NOT NULL DEFAULT 'NORMAL',
    trashed_at timestamp(6),
    trashed_by varchar(64),
    origin_parent_id bigint,
    lock_version integer NOT NULL DEFAULT 0,
    creator varchar(64) DEFAULT '', create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '', update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1))
);
CREATE INDEX drive_entry_parent_idx
    ON public.drive_entry(space_id,parent_id,trash_state,name) WHERE deleted=0;
CREATE UNIQUE INDEX drive_entry_folder_name_uk
    ON public.drive_entry(space_id,parent_id,name) WHERE deleted=0 AND type='FOLDER' AND trash_state='NORMAL';
CREATE INDEX drive_entry_file_idx
    ON public.drive_entry(file_id) WHERE deleted=0;
COMMENT ON TABLE public.drive_entry IS '网盘逻辑节点：目录与文件节点；文件内容在 infra_file，节点只保存展示名称与授权位置';
COMMENT ON COLUMN public.drive_entry.parent_id IS '父节点编号，0 表示空间根目录';
COMMENT ON COLUMN public.drive_entry.type IS '节点类型：FOLDER 目录、FILE 文件';
COMMENT ON COLUMN public.drive_entry.file_id IS '文件节点的内容编号，关联 infra_file.id；目录为空';
COMMENT ON COLUMN public.drive_entry.inherit_parent IS '是否继承上级授权：false 时该节点及其子树忽略祖先授权，仅按本级授权判定';
COMMENT ON COLUMN public.drive_entry.trash_state IS '回收站状态：NORMAL 正常、TRASHED 已移入回收站；回收站内容保留内容记录，只有彻底删除才清理存储';
COMMENT ON COLUMN public.drive_entry.origin_parent_id IS '移入回收站前的父节点，用于恢复时回到原位置';
COMMENT ON COLUMN public.drive_entry.lock_version IS '乐观锁版本，防止移动与重命名并发写坏目录结构';

CREATE TABLE public.drive_permission (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id bigint NOT NULL REFERENCES public.drive_space(id),
    entry_id bigint NOT NULL DEFAULT 0,
    subject_type varchar(16) NOT NULL,
    subject_id bigint NOT NULL,
    role varchar(16) NOT NULL,
    include_children boolean NOT NULL DEFAULT true,
    creator varchar(64) DEFAULT '', create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '', update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1))
);
CREATE UNIQUE INDEX drive_permission_uk
    ON public.drive_permission(space_id,entry_id,subject_type,subject_id) WHERE deleted=0;
CREATE INDEX drive_permission_subject_idx
    ON public.drive_permission(subject_type,subject_id) WHERE deleted=0;
COMMENT ON TABLE public.drive_permission IS '网盘授权：授权到空间或目录节点，对该节点及其子树生效；继承边界由被授权节点的 inherit_parent 决定';
COMMENT ON COLUMN public.drive_permission.entry_id IS '被授权的节点编号，0 表示整个空间';
COMMENT ON COLUMN public.drive_permission.subject_type IS '授权主体类型：USER 用户、DEPT 部门';
COMMENT ON COLUMN public.drive_permission.subject_id IS '授权主体编号：用户编号或部门编号';
COMMENT ON COLUMN public.drive_permission.role IS '授权角色：VIEWER 可查看、EDITOR 可编辑、MANAGER 可管理（含再授权）';
COMMENT ON COLUMN public.drive_permission.include_children IS '部门授权是否含下级部门：true 时主体所在部门为该授权部门的子孙部门也算命中；用户授权忽略该列';

CREATE TABLE public.drive_share (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id bigint NOT NULL REFERENCES public.drive_space(id),
    entry_id bigint NOT NULL,
    role varchar(16) NOT NULL,
    expire_time timestamp(6),
    status varchar(16) NOT NULL DEFAULT 'ACTIVE',
    creator varchar(64) DEFAULT '', create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '', update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1))
);
CREATE INDEX drive_share_entry_idx
    ON public.drive_share(entry_id,status) WHERE deleted=0;
CREATE INDEX drive_share_creator_idx
    ON public.drive_share(creator,status) WHERE deleted=0;
COMMENT ON TABLE public.drive_share IS '网盘组织内分享：一条分享对应一个节点与一组接收主体，到期或撤销后不再授予访问';
COMMENT ON COLUMN public.drive_share.expire_time IS '分享失效时间，为空表示长期有效';
COMMENT ON COLUMN public.drive_share.status IS '分享状态：ACTIVE 生效、REVOKED 已撤销';

CREATE TABLE public.drive_share_subject (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    share_id bigint NOT NULL REFERENCES public.drive_share(id),
    subject_type varchar(16) NOT NULL,
    subject_id bigint NOT NULL,
    creator varchar(64) DEFAULT '', create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '', update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1))
);
CREATE UNIQUE INDEX drive_share_subject_uk
    ON public.drive_share_subject(share_id,subject_type,subject_id) WHERE deleted=0;
CREATE INDEX drive_share_subject_subject_idx
    ON public.drive_share_subject(subject_type,subject_id) WHERE deleted=0;
COMMENT ON TABLE public.drive_share_subject IS '网盘分享接收主体：与分享一对一展开，支持用户与部门';
COMMENT ON COLUMN public.drive_share_subject.subject_type IS '主体类型：USER 用户、DEPT 部门';
COMMENT ON COLUMN public.drive_share_subject.subject_id IS '主体编号：用户编号或部门编号';

CREATE TABLE public.drive_user_mark (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    entry_id bigint NOT NULL,
    mark_type varchar(16) NOT NULL,
    access_time timestamp(6),
    creator varchar(64) DEFAULT '', create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '', update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1))
);
CREATE UNIQUE INDEX drive_user_mark_uk
    ON public.drive_user_mark(user_id,entry_id,mark_type) WHERE deleted=0;
CREATE INDEX drive_user_mark_recent_idx
    ON public.drive_user_mark(user_id,mark_type,access_time DESC) WHERE deleted=0;
COMMENT ON TABLE public.drive_user_mark IS '网盘用户标记：收藏与最近访问，按用户独立，不改变节点授权';
COMMENT ON COLUMN public.drive_user_mark.mark_type IS '标记类型：FAVORITE 收藏、RECENT 最近访问';
COMMENT ON COLUMN public.drive_user_mark.access_time IS '最近访问时间，仅 RECENT 使用';
