-- DEC-20260928-01：网盘与业务融合。前置 V039。
-- 仅新增表与列：业务空间类型经 drive_space.type 新增 BIZ 编码（无 DDL 变更）；drive_entry 增加受管标记；
-- nocode 侧建立业务目录绑定、业务附件绑定、上传会话、保留引用与文件操作任务五张表。
-- 业务文件规则配置随对象版本 schemaJson 冻结，不建独立表；历史附件不迁移。
-- 身份列统一 NOT NULL DEFAULT ''（'' 表示该层级不适用），保证唯一约束对主表与明细行级身份同样生效。
-- 校验：Flyway verify、网盘业务融合专项集成测试（绑定/解绑/保留引用/清理任务）。

-- 受管节点标记：受业务目录规则管理的节点禁止普通网盘操作（移动、重命名、删除、分享、继承变更）
ALTER TABLE public.drive_entry
    ADD COLUMN managed_biz boolean NOT NULL DEFAULT false;
COMMENT ON COLUMN public.drive_entry.managed_biz IS '是否为业务受管节点：由无代码业务规则建立与调整，普通网盘操作入口拒绝修改';

-- 业务目录绑定：对象/记录/明细区/明细行/字段稳定身份 → 目录节点；幂等建目录与目录调整的依据
CREATE TABLE public.nocode_biz_directory_binding (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id varchar(128) NOT NULL,
    record_id varchar(512) NOT NULL,
    detail_id varchar(128) NOT NULL DEFAULT '',
    row_id varchar(128) NOT NULL DEFAULT '',
    field_id varchar(128) NOT NULL DEFAULT '',
    space_id bigint NOT NULL,
    entry_id bigint NOT NULL,
    rule_version int NOT NULL,
    group_keys varchar(512) NOT NULL DEFAULT '',
    creator varchar(64) NOT NULL DEFAULT '',
    create_time timestamp NOT NULL DEFAULT now(),
    updater varchar(64) NOT NULL DEFAULT '',
    update_time timestamp NOT NULL DEFAULT now(),
    deleted smallint NOT NULL DEFAULT 0 CHECK (deleted IN (0,1)),
    CONSTRAINT nocode_biz_directory_binding_uk UNIQUE (object_id, record_id, detail_id, row_id, field_id)
);
CREATE INDEX nocode_biz_directory_binding_entry_idx
    ON public.nocode_biz_directory_binding (space_id, entry_id) WHERE deleted=0;
CREATE INDEX nocode_biz_directory_binding_record_idx
    ON public.nocode_biz_directory_binding (object_id, record_id) WHERE deleted=0;
COMMENT ON TABLE public.nocode_biz_directory_binding IS '业务目录绑定：记录/明细区/明细行/字段身份到网盘目录节点的稳定映射；field_id 为空表示记录/明细区/明细行目录本身';
COMMENT ON COLUMN public.nocode_biz_directory_binding.detail_id IS '所属内部明细稳定 ID，空串表示主表';
COMMENT ON COLUMN public.nocode_biz_directory_binding.row_id IS '内部明细行持久 ID，空串表示非明细行级目录';
COMMENT ON COLUMN public.nocode_biz_directory_binding.field_id IS '附件字段稳定 ID，空串表示记录目录/明细区目录/明细行目录本身';
COMMENT ON COLUMN public.nocode_biz_directory_binding.group_keys IS '业务分组稳定键串（关联记录 ID 等），业务值变更时据此判断是否调整目录';
COMMENT ON COLUMN public.nocode_biz_directory_binding.rule_version IS '建立绑定时生效的对象发布版本号；已有记录沿用该版本，新规则只作用于新记录';

-- 业务附件绑定：业务表 fileId 与网盘文件节点的关联及当前/历史状态
CREATE TABLE public.nocode_biz_attachment_binding (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id varchar(128) NOT NULL,
    record_id varchar(512) NOT NULL,
    detail_id varchar(128) NOT NULL DEFAULT '',
    row_id varchar(128) NOT NULL DEFAULT '',
    field_id varchar(128) NOT NULL,
    file_id bigint NOT NULL,
    entry_id bigint NOT NULL,
    space_id bigint NOT NULL,
    state varchar(16) NOT NULL DEFAULT 'ACTIVE',
    source_entry varchar(32) NOT NULL DEFAULT '',
    creator varchar(64) NOT NULL DEFAULT '',
    create_time timestamp NOT NULL DEFAULT now(),
    updater varchar(64) NOT NULL DEFAULT '',
    update_time timestamp NOT NULL DEFAULT now(),
    deleted smallint NOT NULL DEFAULT 0 CHECK (deleted IN (0,1)),
    CONSTRAINT nocode_biz_attachment_binding_uk UNIQUE (object_id, record_id, detail_id, row_id, field_id, file_id),
    CONSTRAINT nocode_biz_attachment_binding_state_ck CHECK (state IN ('ACTIVE','HISTORY'))
);
CREATE INDEX nocode_biz_attachment_binding_file_idx
    ON public.nocode_biz_attachment_binding (file_id) WHERE deleted=0;
CREATE INDEX nocode_biz_attachment_binding_record_idx
    ON public.nocode_biz_attachment_binding (object_id, record_id) WHERE deleted=0;
CREATE INDEX nocode_biz_attachment_binding_state_idx
    ON public.nocode_biz_attachment_binding (file_id, state) WHERE deleted=0;
COMMENT ON TABLE public.nocode_biz_attachment_binding IS '业务附件绑定：字段值中的 fileId 与网盘文件节点/空间的对应关系；移除附件转 HISTORY，不物理删除';
COMMENT ON COLUMN public.nocode_biz_attachment_binding.state IS 'ACTIVE 当前有效、HISTORY 已从当前值移除但历史引用仍保留';
COMMENT ON COLUMN public.nocode_biz_attachment_binding.source_entry IS '上传来源入口标识（应用/维护/任务），仅作来源信息，不参与归属判定';

-- 上传会话：受保护临时上传的归属与有效期；仅业务接入字段使用，普通系统附件不登记
CREATE TABLE public.nocode_biz_upload_session (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_key varchar(64) NOT NULL,
    user_id bigint NOT NULL,
    object_id varchar(128) NOT NULL,
    field_id varchar(128) NOT NULL,
    record_id varchar(512),
    file_id bigint NOT NULL,
    file_name varchar(255) NOT NULL,
    state varchar(16) NOT NULL DEFAULT 'TEMPORARY',
    expires_at timestamp NOT NULL,
    idempotency_key varchar(128) NOT NULL DEFAULT '',
    creator varchar(64) NOT NULL DEFAULT '',
    create_time timestamp NOT NULL DEFAULT now(),
    updater varchar(64) NOT NULL DEFAULT '',
    update_time timestamp NOT NULL DEFAULT now(),
    deleted smallint NOT NULL DEFAULT 0 CHECK (deleted IN (0,1)),
    CONSTRAINT nocode_biz_upload_session_uk UNIQUE (session_key, file_id),
    CONSTRAINT nocode_biz_upload_session_state_ck CHECK (state IN ('TEMPORARY','BOUND','EXPIRED','CLEANED'))
);
CREATE INDEX nocode_biz_upload_session_expire_idx
    ON public.nocode_biz_upload_session (state, expires_at) WHERE deleted=0;
CREATE INDEX nocode_biz_upload_session_file_idx
    ON public.nocode_biz_upload_session (file_id) WHERE deleted=0;
-- 幂等键只在显式提供时约束；空串表示未使用幂等，不参与唯一性
CREATE UNIQUE INDEX nocode_biz_upload_session_idem_uk
    ON public.nocode_biz_upload_session (user_id, idempotency_key)
    WHERE deleted=0 AND idempotency_key <> '';
COMMENT ON TABLE public.nocode_biz_upload_session IS '业务附件受保护上传会话：保存成功前仅上传者可用；有效期默认 24 小时，被有效草稿引用时续留';
COMMENT ON COLUMN public.nocode_biz_upload_session.state IS 'TEMPORARY 待保存、BOUND 已绑定记录、EXPIRED 已过期待清理、CLEANED 已清理';
COMMENT ON COLUMN public.nocode_biz_upload_session.idempotency_key IS '上传幂等键，同一用户重复提交不重复登记；空串表示不使用幂等';

-- 保留引用：业务修订、草稿、提交材料等持有者对文件的引用，阻止误删
CREATE TABLE public.nocode_biz_file_retention (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id bigint NOT NULL,
    holder_type varchar(32) NOT NULL,
    holder_id varchar(128) NOT NULL,
    object_id varchar(128) NOT NULL,
    record_id varchar(512),
    creator varchar(64) NOT NULL DEFAULT '',
    create_time timestamp NOT NULL DEFAULT now(),
    updater varchar(64) NOT NULL DEFAULT '',
    update_time timestamp NOT NULL DEFAULT now(),
    deleted smallint NOT NULL DEFAULT 0 CHECK (deleted IN (0,1)),
    CONSTRAINT nocode_biz_file_retention_uk UNIQUE (file_id, holder_type, holder_id)
);
CREATE INDEX nocode_biz_file_retention_file_idx
    ON public.nocode_biz_file_retention (file_id) WHERE deleted=0;
COMMENT ON TABLE public.nocode_biz_file_retention IS '文件保留引用：历史修订/工作草稿/提交材料等持有者的登记；有有效引用的文件不进入物理清理';
COMMENT ON COLUMN public.nocode_biz_file_retention.holder_type IS '持有者类型：RECORD_HISTORY 记录历史、WORK_DRAFT 工作草稿、WORK_SUBMISSION 提交材料';

-- 文件操作任务：对象存储补偿清理、目录批量整理、对账的执行状态与重试记录
CREATE TABLE public.nocode_biz_file_task (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type varchar(32) NOT NULL,
    file_id bigint,
    payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    state varchar(16) NOT NULL DEFAULT 'PENDING',
    attempts integer NOT NULL DEFAULT 0,
    last_error varchar(2000),
    creator varchar(64) NOT NULL DEFAULT '',
    create_time timestamp NOT NULL DEFAULT now(),
    updater varchar(64) NOT NULL DEFAULT '',
    update_time timestamp NOT NULL DEFAULT now(),
    deleted smallint NOT NULL DEFAULT 0 CHECK (deleted IN (0,1)),
    CONSTRAINT nocode_biz_file_task_state_ck CHECK (state IN ('PENDING','RUNNING','DONE','FAILED'))
);
CREATE INDEX nocode_biz_file_task_state_idx
    ON public.nocode_biz_file_task (task_type, state) WHERE deleted=0;
COMMENT ON TABLE public.nocode_biz_file_task IS '文件操作任务：物理删除补偿、目录整理等异步动作的持久状态；只登记已知操作，不扫描无归属文件';
