-- 记录文件夹：对象上的文件夹来源配置，以及「记录 → 网盘文件夹」的对应关系。前置 V046。
-- 仅新增三张表；不改任何既有表、不动菜单与权限码。配置不随对象版本冻结，保存即生效。
-- 校验：Flyway verify、记录文件夹专项集成测试（配置校验 / 解析 / 首次写入建目录 / 越界拒绝）。

CREATE TABLE public.nocode_record_folder_source (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id varchar(128) NOT NULL,
    sort_no int NOT NULL DEFAULT 0,
    label varchar(40) NOT NULL DEFAULT '',
    kind varchar(16) NOT NULL,
    placement varchar(24) NOT NULL,
    space_id bigint,
    entry_id bigint,
    relation_field_id varchar(128) NOT NULL DEFAULT '',
    target_source_id bigint,
    create_mode varchar(16) NOT NULL DEFAULT 'ON_FIRST_WRITE',
    name_template varchar(2000) NOT NULL DEFAULT '',
    creator varchar(64) NOT NULL DEFAULT '',
    create_time timestamp NOT NULL DEFAULT now(),
    updater varchar(64) NOT NULL DEFAULT '',
    update_time timestamp NOT NULL DEFAULT now(),
    deleted smallint NOT NULL DEFAULT 0 CHECK (deleted IN (0,1)),
    CONSTRAINT nocode_record_folder_source_kind CHECK (kind IN ('FOLDER','RELATION')),
    CONSTRAINT nocode_record_folder_source_placement CHECK (placement IN ('DIRECT','RECORD_SUBFOLDER')),
    CONSTRAINT nocode_record_folder_source_create_mode CHECK (create_mode IN ('ON_FIRST_WRITE','ON_SAVE')),
    CONSTRAINT nocode_record_folder_source_shape CHECK (
        (kind = 'FOLDER'   AND space_id IS NOT NULL AND entry_id IS NOT NULL
                           AND relation_field_id = '' AND target_source_id IS NULL)
     OR (kind = 'RELATION' AND space_id IS NULL AND entry_id IS NULL
                           AND relation_field_id <> '' AND target_source_id IS NOT NULL))
);
CREATE INDEX nocode_record_folder_source_object_idx
    ON public.nocode_record_folder_source (object_id, sort_no) WHERE deleted = 0;
CREATE INDEX nocode_record_folder_source_target_idx
    ON public.nocode_record_folder_source (target_source_id) WHERE deleted = 0;
COMMENT ON TABLE public.nocode_record_folder_source IS '记录文件夹来源：一行 = 某对象表单下方的一个文件夹页签；不随对象版本冻结';
COMMENT ON COLUMN public.nocode_record_folder_source.kind IS 'FOLDER 指定网盘里的一个文件夹；RELATION 用关联记录的文件夹';
COMMENT ON COLUMN public.nocode_record_folder_source.placement IS 'DIRECT 直接用那个文件夹；RECORD_SUBFOLDER 在其中为本记录建一个子文件夹';
COMMENT ON COLUMN public.nocode_record_folder_source.entry_id IS 'FOLDER：指定的网盘目录节点编号（普通节点）';
COMMENT ON COLUMN public.nocode_record_folder_source.relation_field_id IS 'RELATION：本对象主表上的单值关联字段稳定 ID';
COMMENT ON COLUMN public.nocode_record_folder_source.target_source_id IS 'RELATION：对方对象的文件夹来源编号';
COMMENT ON COLUMN public.nocode_record_folder_source.create_mode IS '子文件夹的建立时机：ON_FIRST_WRITE 第一次写入时；ON_SAVE 记录保存提交后由后台建立。仅 RECORD_SUBFOLDER 有意义';
COMMENT ON COLUMN public.nocode_record_folder_source.name_template IS '子文件夹命名模板的 JSON 文本；空串表示用记录名称。仅 RECORD_SUBFOLDER 有意义';

CREATE TABLE public.nocode_record_folder_binding (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id varchar(128) NOT NULL,
    record_id varchar(512) NOT NULL,
    source_id bigint NOT NULL,
    anchor_entry_id bigint NOT NULL DEFAULT 0,
    space_id bigint NOT NULL,
    entry_id bigint NOT NULL,
    origin varchar(16) NOT NULL DEFAULT 'AUTO',
    auto_name varchar(255) NOT NULL DEFAULT '',
    creator varchar(64) NOT NULL DEFAULT '',
    create_time timestamp NOT NULL DEFAULT now(),
    updater varchar(64) NOT NULL DEFAULT '',
    update_time timestamp NOT NULL DEFAULT now(),
    deleted smallint NOT NULL DEFAULT 0 CHECK (deleted IN (0,1)),
    CONSTRAINT nocode_record_folder_binding_origin CHECK (origin IN ('AUTO','MANUAL'))
);
CREATE UNIQUE INDEX nocode_record_folder_binding_uk
    ON public.nocode_record_folder_binding (object_id, record_id, source_id, anchor_entry_id)
    WHERE deleted = 0;
CREATE INDEX nocode_record_folder_binding_entry_idx
    ON public.nocode_record_folder_binding (entry_id) WHERE deleted = 0;
COMMENT ON TABLE public.nocode_record_folder_binding IS '记录文件夹对应关系：记录在某来源下的子文件夹；按网盘节点编号绑定，文件夹改名或移动不影响';
COMMENT ON COLUMN public.nocode_record_folder_binding.anchor_entry_id IS '子文件夹建在谁下面：FOLDER 来源恒为 0；RELATION 来源为关联记录解析出的文件夹编号';
COMMENT ON COLUMN public.nocode_record_folder_binding.origin IS 'AUTO 系统在首次写入时建立；MANUAL 人工指定（二期）';
COMMENT ON COLUMN public.nocode_record_folder_binding.auto_name IS '建立时系统取的名字，供二期判断文件夹是否被人工改过名';

-- 网盘节点的来源标记：经由业务表单放进去的节点记一笔「是哪条记录放的」；只在创建时写一次，之后不改。
CREATE TABLE public.drive_entry_origin (
    entry_id bigint PRIMARY KEY,
    origin_key varchar(700) NOT NULL,
    creator varchar(64) NOT NULL DEFAULT '',
    create_time timestamp NOT NULL DEFAULT now(),
    updater varchar(64) NOT NULL DEFAULT '',
    update_time timestamp NOT NULL DEFAULT now(),
    deleted smallint NOT NULL DEFAULT 0 CHECK (deleted IN (0,1))
);
CREATE INDEX drive_entry_origin_key_idx ON public.drive_entry_origin (origin_key) WHERE deleted = 0;
COMMENT ON TABLE public.drive_entry_origin IS '网盘节点来源标记：节点经由哪个业务来源放入；对网盘是不透明字符串。没有有效行（deleted = 0）= 没有来源（直接在网盘里放的）';
COMMENT ON COLUMN public.drive_entry_origin.origin_key IS '来源键；无代码侧写入「对象编号:记录编号」';
