-- 业务动作「按日期自动执行」的执行账本。前置 V047。
-- 规则本身仍在应用发布快照里（自动更新 mode=DATE），这里只记「每条规则封账到哪一天」与「每天哪条来源记录已处理」。
-- 影响范围：新增两张表；不改任何现有表与数据。应用的行被物理删除时（正式环境只做逻辑删除；集成测试夹具清理会物理删除）账本随之删除。
-- 校验：SELECT count(*) FROM public.nocode_date_trigger_state; 迁移后应为 0。
--       SELECT count(*) FROM public.nocode_date_trigger_done;  迁移后应为 0。
CREATE TABLE public.nocode_date_trigger_state (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES public.nocode_application(id) ON DELETE CASCADE,
    resource_id varchar(64) NOT NULL,
    armed boolean NOT NULL DEFAULT true,
    closed_date date NOT NULL,
    armed_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_scan_at timestamp(6),
    last_scan_date date,
    last_trigger varchar(16),
    last_error varchar(1000),
    creator varchar(64) DEFAULT '', create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '', update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1)),
    CONSTRAINT nocode_date_trigger_state_uk UNIQUE (application_id, resource_id),
    CONSTRAINT nocode_date_trigger_state_trigger CHECK (last_trigger IS NULL OR last_trigger IN ('AUTO','MANUAL'))
);
COMMENT ON TABLE public.nocode_date_trigger_state IS '按日期自动执行：每条规则的账本；closed_date 及以前的日期不再处理';

CREATE TABLE public.nocode_date_trigger_done (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES public.nocode_application(id) ON DELETE CASCADE,
    resource_id varchar(64) NOT NULL,
    business_date date NOT NULL,
    source_record_id varchar(500) NOT NULL,
    outcome varchar(16) NOT NULL,
    target_count integer NOT NULL DEFAULT 0,
    message varchar(1000),
    done_at timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creator varchar(64) DEFAULT '', create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '', update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1)),
    CONSTRAINT nocode_date_trigger_done_uk UNIQUE (application_id, resource_id, business_date, source_record_id),
    CONSTRAINT nocode_date_trigger_done_outcome CHECK (outcome IN ('RUNNING','SUCCESS','UNCHANGED','FAILED'))
);
CREATE INDEX nocode_date_trigger_done_date ON public.nocode_date_trigger_done(business_date);
COMMENT ON TABLE public.nocode_date_trigger_done IS '按日期自动执行：某规则某业务日已处理的来源记录（同一天不重复执行的唯一性）；保留 90 天';
