-- 提前落地报表资源反向依赖索引，供数据集删除预检及后续仪表板/应用固定引用共用。
-- 对象/字段依赖仍由 nocode_resource_dependency 维护，不复制业务数据。
CREATE TABLE public.nocode_report_dependency (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_kind varchar(32) NOT NULL CHECK (source_kind IN ('DASHBOARD','APPLICATION')),
    source_id bigint NOT NULL,
    source_stage varchar(16) NOT NULL CHECK (source_stage IN ('DRAFT','VERSION')),
    source_version integer NOT NULL CHECK (source_version >= 0),
    target_kind varchar(32) NOT NULL CHECK (target_kind IN ('DATASET','DASHBOARD')),
    target_id bigint NOT NULL,
    target_version integer NOT NULL CHECK (target_version > 0),
    field_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(field_refs_json)='array'),
    creator varchar(64) NOT NULL DEFAULT '', create_time timestamp NOT NULL DEFAULT now(),
    updater varchar(64) NOT NULL DEFAULT '', update_time timestamp NOT NULL DEFAULT now(),
    deleted smallint NOT NULL DEFAULT 0 CHECK (deleted IN (0,1)),
    CHECK ((source_stage='DRAFT' AND source_version=0) OR (source_stage='VERSION' AND source_version>0)),
    UNIQUE(source_kind,source_id,source_stage,source_version,target_kind,target_id,target_version)
);
CREATE INDEX nocode_report_dependency_target_idx ON public.nocode_report_dependency(target_kind,target_id) WHERE deleted=0;
COMMENT ON TABLE public.nocode_report_dependency IS '报表固定引用反向索引，保留草稿及可恢复历史版本；写入方须先持全局设计锁并校验目标未删除';
