-- 仪表板分类与停用属于资源头，不改写任何已发布内容或校验和。
ALTER TABLE public.nocode_report_dashboard
    ADD COLUMN status varchar(16) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','INACTIVE')),
    ADD COLUMN folder_id bigint REFERENCES public.nocode_report_folder(id);
CREATE INDEX nocode_report_dashboard_folder_idx
    ON public.nocode_report_dashboard(folder_id) WHERE deleted=0;
CREATE INDEX nocode_report_dashboard_status_idx
    ON public.nocode_report_dashboard(status,update_time DESC,id DESC) WHERE deleted=0;
COMMENT ON COLUMN public.nocode_report_dashboard.status IS '停用作用于全部发布版本；发布不自动激活显式停用资源';
COMMENT ON COLUMN public.nocode_report_dashboard.folder_id IS '同类型分类目录，不参与发布快照及内容校验和';

CREATE TABLE public.nocode_report_preference (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    dashboard_id bigint NOT NULL REFERENCES public.nocode_report_dashboard(id),
    favorite boolean NOT NULL DEFAULT false,
    last_visited_at timestamp,
    creator varchar(64) NOT NULL DEFAULT '',
    create_time timestamp NOT NULL DEFAULT now(),
    updater varchar(64) NOT NULL DEFAULT '',
    update_time timestamp NOT NULL DEFAULT now(),
    deleted smallint NOT NULL DEFAULT 0 CHECK (deleted IN (0,1)),
    UNIQUE(user_id,dashboard_id)
);
CREATE INDEX nocode_report_preference_recent_idx
    ON public.nocode_report_preference(user_id,last_visited_at DESC,dashboard_id DESC)
    WHERE deleted=0 AND last_visited_at IS NOT NULL;
CREATE INDEX nocode_report_preference_favorite_idx
    ON public.nocode_report_preference(user_id,update_time DESC,dashboard_id DESC)
    WHERE deleted=0 AND favorite;
COMMENT ON TABLE public.nocode_report_preference IS '个人仪表板收藏与最近访问；读取实时过滤当前资源访问权限';

-- 复用现有报表中心菜单和动态路由；不替普通角色自动授予资源或系统权限。
-- 仅调整两个已知入口的默认顺序，不改权限、路由身份或其他自定义菜单排序。
UPDATE public.system_menu SET sort=1,updater='report-lifecycle-migration',update_time=now()
WHERE path='/nocode/report-center/dashboards' AND sort=0 AND deleted=0
    AND parent_id IN (SELECT id FROM public.system_menu WHERE path='/nocode/report-center' AND deleted=0);
UPDATE public.system_menu SET sort=2,updater='report-lifecycle-migration',update_time=now()
WHERE path='/nocode/report-center/datasets' AND sort=1 AND deleted=0
    AND parent_id IN (SELECT id FROM public.system_menu WHERE path='/nocode/report-center' AND deleted=0);
INSERT INTO public.system_menu(id,name,permission,type,sort,parent_id,path,icon,component,component_name,status,visible,keep_alive,always_show,creator,updater,create_time,update_time,deleted)
SELECT nextval('public.system_menu_seq'),'报表工作台','nocode:report:query',2,0,id,
    '/nocode/report-center/home','HomeOutlined','nocode/report-center/home','NocodeReportHome',
    0,true,false,true,'report-lifecycle-migration','report-lifecycle-migration',now(),now(),0
FROM public.system_menu WHERE path='/nocode/report-center' AND deleted=0;
