-- B1: platform metadata only. Saving an object draft never executes this migration.
CREATE SEQUENCE public.lc_stable_id_seq AS bigint;

CREATE TABLE public.lc_object (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 object_code varchar(64) NOT NULL UNIQUE,
 object_name varchar(128) NOT NULL,
 source_type varchar(24) NOT NULL DEFAULT 'GENERATED',
 physical_name_seed varchar(48) NOT NULL UNIQUE,
 title_field_stable_id bigint NOT NULL,
 title_template varchar(512),
 title_config_json jsonb NOT NULL DEFAULT '{}',
 owner_field_stable_id bigint,
 org_field_stable_id bigint,
 latest_version_no integer NOT NULL DEFAULT 1,
 current_published_version_no integer,
 description varchar(1000),
 status varchar(24) NOT NULL DEFAULT 'DRAFT',
 created_by bigint NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_by bigint NOT NULL,
 updated_at timestamptz NOT NULL DEFAULT now(),
 lock_version integer NOT NULL DEFAULT 0 CHECK (lock_version >= 0),
 CONSTRAINT lc_object_title_choice CHECK (title_template IS NULL)
);
COMMENT ON TABLE public.lc_object IS '全局数据对象；草稿保存不创建业务表';

CREATE TABLE public.lc_object_version (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 object_id bigint NOT NULL REFERENCES public.lc_object(id),
 version_no integer NOT NULL,
 base_version_no integer,
 schema_version integer NOT NULL DEFAULT 1,
 state varchar(24) NOT NULL DEFAULT 'DRAFT',
 schema_json jsonb NOT NULL,
 schema_checksum char(64) NOT NULL,
 change_summary_json jsonb NOT NULL DEFAULT '{}',
 created_by bigint NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(),
 published_by bigint,
 published_at timestamptz,
 lock_version integer NOT NULL DEFAULT 0,
 UNIQUE(object_id, version_no),
 UNIQUE(object_id, schema_checksum)
);
CREATE UNIQUE INDEX lc_object_one_draft ON public.lc_object_version(object_id) WHERE state = 'DRAFT';

CREATE TABLE public.lc_object_table (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 object_version_id bigint NOT NULL REFERENCES public.lc_object_version(id),
 stable_table_id bigint NOT NULL,
 table_code varchar(64) NOT NULL,
 table_name varchar(63) NOT NULL,
 table_role varchar(24) NOT NULL CHECK(table_role IN ('MAIN', 'DETAIL')),
 parent_stable_table_id bigint,
 detail_no integer,
 config_json jsonb NOT NULL DEFAULT '{}',
 UNIQUE(object_version_id, stable_table_id),
 UNIQUE(object_version_id, table_code),
 UNIQUE(object_version_id, table_name)
);
CREATE UNIQUE INDEX lc_object_one_main ON public.lc_object_table(object_version_id) WHERE table_role = 'MAIN';

CREATE TABLE public.lc_field (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 object_version_id bigint NOT NULL REFERENCES public.lc_object_version(id),
 object_table_id bigint NOT NULL REFERENCES public.lc_object_table(id),
 stable_field_id bigint NOT NULL,
 field_code varchar(64) NOT NULL,
 field_name varchar(128) NOT NULL,
 column_name varchar(63) NOT NULL,
 data_type varchar(32) NOT NULL,
 storage_type varchar(24) NOT NULL DEFAULT 'COLUMN',
 length_value integer,
 precision_value integer,
 scale_value integer,
 required_flag boolean NOT NULL DEFAULT false,
 unique_flag boolean NOT NULL DEFAULT false,
 data_classification varchar(24) NOT NULL DEFAULT 'NORMAL',
 default_value_ast jsonb,
 validation_ast jsonb,
 field_state varchar(24) NOT NULL DEFAULT 'ACTIVE',
 relation_generated boolean NOT NULL DEFAULT false,
 display_resolver_type varchar(24) NOT NULL DEFAULT 'NONE',
 display_resolver_target_id bigint,
 option_set_json jsonb NOT NULL DEFAULT '[]',
 display_config_json jsonb NOT NULL DEFAULT '{}',
 config_json jsonb NOT NULL DEFAULT '{}',
 UNIQUE(object_version_id, stable_field_id),
 UNIQUE(object_table_id, field_code) DEFERRABLE INITIALLY DEFERRED,
 UNIQUE(object_table_id, column_name) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX lc_field_stable_version ON public.lc_field(stable_field_id, object_version_id);

CREATE TABLE public.aud_operation_log (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 occurred_at timestamptz NOT NULL DEFAULT now(),
 trace_id uuid NOT NULL,
 correlation_id uuid,
 operator_id bigint,
 app_id bigint,
 operation_type varchar(64) NOT NULL,
 resource_type varchar(64) NOT NULL,
 resource_id varchar(128),
 object_id bigint,
 business_id bigint,
 result_status varchar(24) NOT NULL,
 reason varchar(1000),
 client_ip inet,
 user_agent varchar(1000),
 detail_json jsonb NOT NULL DEFAULT '{}'
);
CREATE INDEX aud_operation_resource ON public.aud_operation_log(resource_type, resource_id, occurred_at DESC);
COMMENT ON TABLE public.aud_operation_log IS '操作审计；B1 保存成功与对象元数据同事务';

