-- Preserve B1 audit identities and instants while aligning with the OS BaseDO contract.
-- OS displays local timestamps in Asia/Shanghai; historical metadata used timestamptz.
ALTER TABLE public.nocode_object RENAME COLUMN created_by TO creator;
ALTER TABLE public.nocode_object RENAME COLUMN updated_by TO updater;
ALTER TABLE public.nocode_object RENAME COLUMN created_at TO create_time;
ALTER TABLE public.nocode_object RENAME COLUMN updated_at TO update_time;
ALTER TABLE public.nocode_object_version RENAME COLUMN created_by TO creator;
ALTER TABLE public.nocode_object_version RENAME COLUMN created_at TO create_time;
ALTER TABLE public.nocode_object ALTER COLUMN creator TYPE varchar(64) USING creator::text,
  ALTER COLUMN updater TYPE varchar(64) USING updater::text,
  ALTER COLUMN create_time TYPE timestamp(6) without time zone USING create_time AT TIME ZONE 'Asia/Shanghai',
  ALTER COLUMN update_time TYPE timestamp(6) without time zone USING update_time AT TIME ZONE 'Asia/Shanghai';
ALTER TABLE public.nocode_object_version ALTER COLUMN creator TYPE varchar(64) USING creator::text,
  ALTER COLUMN create_time TYPE timestamp(6) without time zone USING create_time AT TIME ZONE 'Asia/Shanghai';

-- DC: versioned object design and explicit deployment governance. Business DDL is never run here.
ALTER TABLE public.nocode_object ADD COLUMN schema_name varchar(63) NOT NULL DEFAULT 'public';
ALTER TABLE public.nocode_object ADD COLUMN settings_json jsonb NOT NULL DEFAULT '{}';
ALTER TABLE public.nocode_object ADD COLUMN read_only boolean NOT NULL DEFAULT false;
ALTER TABLE public.nocode_object ADD COLUMN adoption_hash varchar(64);
ALTER TABLE public.nocode_object DROP CONSTRAINT nocode_object_title_choice;

-- A new draft starts with the same design as its published predecessor.
DO $$
DECLARE c record;
BEGIN
  FOR c IN SELECT conname FROM pg_constraint
    WHERE conrelid='public.nocode_object_version'::regclass AND contype='u'
      AND pg_get_constraintdef(oid) LIKE '%schema_checksum%'
  LOOP
    EXECUTE format('ALTER TABLE public.nocode_object_version DROP CONSTRAINT %I', c.conname);
  END LOOP;
END $$;

CREATE TABLE public.nocode_relation (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  object_version_id bigint NOT NULL REFERENCES public.nocode_object_version(id),
  stable_relation_id bigint NOT NULL,
  relation_code varchar(63) NOT NULL,
  relation_name varchar(128) NOT NULL,
  relation_kind varchar(24) NOT NULL CHECK (relation_kind IN ('REFERENCE','MASTER_DETAIL','ONE_TO_ONE','MANY_TO_MANY')),
  target_object_id bigint NOT NULL REFERENCES public.nocode_object(id),
  field_stable_id bigint,
  target_field_stable_id bigint,
  required_flag boolean NOT NULL DEFAULT false,
  on_delete varchar(16) NOT NULL CHECK (on_delete IN ('RESTRICT','CASCADE','SET_NULL')),
  UNIQUE(object_version_id, stable_relation_id),
  UNIQUE(object_version_id, relation_code)
);
CREATE INDEX nocode_relation_target ON public.nocode_relation(target_object_id);

CREATE TABLE public.nocode_index_definition (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  object_version_id bigint NOT NULL REFERENCES public.nocode_object_version(id),
  stable_index_id bigint NOT NULL,
  index_code varchar(63) NOT NULL,
  index_name varchar(128) NOT NULL,
  unique_flag boolean NOT NULL DEFAULT false,
  field_ids_json jsonb NOT NULL,
  UNIQUE(object_version_id, stable_index_id),
  UNIQUE(object_version_id, index_code)
);

CREATE TABLE public.nocode_publish_plan (
  id uuid PRIMARY KEY,
  object_id bigint NOT NULL REFERENCES public.nocode_object(id),
  object_version_id bigint NOT NULL REFERENCES public.nocode_object_version(id),
  version_no integer NOT NULL,
  revision integer NOT NULL,
  schema_checksum char(64) NOT NULL,
  baseline_hash varchar(64) NOT NULL,
  plan_json jsonb NOT NULL,
  state varchar(24) NOT NULL DEFAULT 'PENDING',
  creator varchar(64) NOT NULL,
  create_time timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  executed_by bigint,
  executed_at timestamptz,
  reason varchar(1000),
  error_message varchar(1000)
);
CREATE INDEX nocode_publish_plan_object ON public.nocode_publish_plan(object_id, create_time DESC);

CREATE TABLE public.nocode_deployment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  object_id bigint NOT NULL REFERENCES public.nocode_object(id),
  version_no integer NOT NULL,
  schema_name varchar(63) NOT NULL,
  table_name varchar(63) NOT NULL,
  structure_hash char(64) NOT NULL,
  structure_json jsonb NOT NULL,
  verified_at timestamptz NOT NULL DEFAULT now(),
  deployed_by bigint NOT NULL,
  deployed_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(object_id, version_no)
);

CREATE TABLE public.nocode_resource_dependency (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_kind varchar(32) NOT NULL,
  source_key varchar(160) NOT NULL,
  source_name varchar(160) NOT NULL,
  target_object_id bigint NOT NULL REFERENCES public.nocode_object(id),
  field_ids_json jsonb NOT NULL DEFAULT '[]',
  update_time timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(source_kind, source_key, target_object_id)
);

-- All application-owned metadata tables share BaseDO. Flyway owns its history table.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['nocode_object','nocode_object_version','nocode_object_table','nocode_field',
    'nocode_operation_log','nocode_relation','nocode_index_definition','nocode_publish_plan',
    'nocode_deployment','nocode_resource_dependency'] LOOP
    EXECUTE format('ALTER TABLE public.%I ADD COLUMN IF NOT EXISTS creator varchar(64) DEFAULT '''',
      ADD COLUMN IF NOT EXISTS create_time timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
      ADD COLUMN IF NOT EXISTS updater varchar(64) DEFAULT '''',
      ADD COLUMN IF NOT EXISTS update_time timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
      ADD COLUMN deleted smallint NOT NULL DEFAULT 0 CHECK (deleted IN (0,1))',t);
    EXECUTE format('COMMENT ON COLUMN public.%I.creator IS ''创建者（底座用户 ID）''',t);
    EXECUTE format('COMMENT ON COLUMN public.%I.create_time IS ''创建时间''',t);
    EXECUTE format('COMMENT ON COLUMN public.%I.updater IS ''更新者（底座用户 ID）''',t);
    EXECUTE format('COMMENT ON COLUMN public.%I.update_time IS ''更新时间''',t);
    EXECUTE format('COMMENT ON COLUMN public.%I.deleted IS ''是否删除：0 否，1 是''',t);
  END LOOP;
END $$;
UPDATE public.nocode_object_version v SET updater=o.updater,update_time=o.update_time
  FROM public.nocode_object o WHERE o.id=v.object_id;
UPDATE public.nocode_object_table t SET creator=v.creator,create_time=v.create_time,updater=v.updater,update_time=v.update_time
  FROM public.nocode_object_version v WHERE v.id=t.object_version_id;
UPDATE public.nocode_field f SET creator=v.creator,create_time=v.create_time,updater=v.updater,update_time=v.update_time
  FROM public.nocode_object_version v WHERE v.id=f.object_version_id;
UPDATE public.nocode_operation_log SET creator=coalesce(operator_id::text,''),updater=coalesce(operator_id::text,''),
  create_time=occurred_at AT TIME ZONE 'Asia/Shanghai',update_time=occurred_at AT TIME ZONE 'Asia/Shanghai';

COMMENT ON TABLE public.nocode_relation IS '对象版本内的稳定关系定义；引用字段由关系维护';
COMMENT ON TABLE public.nocode_publish_plan IS '绑定草稿修订与物理指纹的结构发布计划及执行结果';
COMMENT ON TABLE public.nocode_deployment IS '每次结构发布后的实际物理结构基线';
COMMENT ON TABLE public.nocode_resource_dependency IS '应用、页面、视图、流程等模块登记的对象及字段依赖';

DO $$
DECLARE p bigint; o bigint; t bigint; e record;
BEGIN
  SELECT parent_id, id INTO p, o FROM public.system_menu WHERE permission='nocode:object:query' AND deleted=0;
  IF p IS NULL THEN RAISE EXCEPTION 'Install object menus first'; END IF;
  IF EXISTS(SELECT 1 FROM public.system_menu WHERE path='/nocode/table' AND deleted=0) THEN
    RAISE EXCEPTION 'Data-table menu path is already occupied';
  END IF;
  t := nextval('public.system_menu_seq');
  INSERT INTO public.system_menu(id,name,permission,type,sort,parent_id,path,icon,component,component_name,status,visible,keep_alive,always_show,creator,updater,create_time,update_time,deleted)
  VALUES(t,'数据表','nocode:table:query',2,2,p,'/nocode/table','DatabaseOutlined','nocode/table/index','NocodeTable',0,true,true,true,'nocode-migration','nocode-migration',now(),now(),0);
  FOR e IN SELECT * FROM (VALUES
    ('发布对象结构','nocode:object:publish',o),('对象生命周期','nocode:object:manage',o),
    ('已有表纳管','nocode:object:adopt',o),('导入对象结构','nocode:object:import',o),
    ('数据只读预览','nocode:table:preview',t),('查看系统表结构','nocode:table:system',t)
  ) AS x(name,permission,parent_id) LOOP
    INSERT INTO public.system_menu(id,name,permission,type,sort,parent_id,path,status,visible,keep_alive,always_show,creator,updater,create_time,update_time,deleted)
    VALUES(nextval('public.system_menu_seq'),e.name,e.permission,3,10,e.parent_id,'',0,true,false,false,'nocode-migration','nocode-migration',now(),now(),0);
  END LOOP;
END $$;
