-- 应用只引用全局对象，业务数据不复制到应用配置表。
CREATE TABLE public.nocode_application (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_code varchar(64) NOT NULL UNIQUE,
    app_name varchar(160) NOT NULL,
    description varchar(2000),
    icon varchar(80),
    status varchar(20) NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','DISABLED')),
    lock_version integer NOT NULL DEFAULT 0,
    published_version integer,
    design_json jsonb NOT NULL DEFAULT '{"objects":[],"resources":[]}'::jsonb CHECK(jsonb_typeof(design_json)='object'),
    creator varchar(64) DEFAULT '', create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '', update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1))
);
CREATE TABLE public.nocode_application_version (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES public.nocode_application(id),
    version_no integer NOT NULL CHECK(version_no>0),
    definition_json jsonb NOT NULL CHECK(jsonb_typeof(definition_json)='object'),
    checksum varchar(64) NOT NULL,
    reason varchar(1000) NOT NULL,
    creator varchar(64) DEFAULT '', create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '', update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1)),
    UNIQUE(application_id,version_no)
);
COMMENT ON TABLE public.nocode_application IS '应用头与编辑草稿；业务数据仍属于全局对象';
COMMENT ON TABLE public.nocode_application_version IS '不可变应用发布版本，保存精确对象引用和资源配置';
DO $$
DECLARE p bigint; a bigint; e record;
BEGIN
    LOCK TABLE public.system_menu IN SHARE ROW EXCLUSIVE MODE;
    IF EXISTS(SELECT 1 FROM public.system_menu WHERE deleted=0 AND (path='/nocode-app' OR permission LIKE 'nocode:app:%')) THEN
        RAISE EXCEPTION 'Application-center menu or permission already exists';
    END IF;
    p:=nextval('public.system_menu_seq');
    a:=nextval('public.system_menu_seq');
    INSERT INTO public.system_menu(id,name,permission,type,sort,parent_id,path,icon,component,status,visible,keep_alive,always_show,creator,updater,create_time,update_time,deleted)
    VALUES(p,'应用中心','',1,26,0,'/nocode-app','AppstoreOutlined',NULL,0,true,true,true,'nocode-migration','nocode-migration',now(),now(),0);
    INSERT INTO public.system_menu(id,name,permission,type,sort,parent_id,path,icon,component,component_name,status,visible,keep_alive,always_show,creator,updater,create_time,update_time,deleted)
    VALUES(a,'应用管理','nocode:app:query',2,1,p,'/nocode-app/application','AppstoreOutlined','nocode/application/index','NocodeApplication',0,true,true,true,'nocode-migration','nocode-migration',now(),now(),0);
    FOR e IN SELECT * FROM (VALUES
        ('创建应用','nocode:app:create'),('编辑应用','nocode:app:update'),('发布应用','nocode:app:publish'),('管理应用','nocode:app:manage')
    ) AS v(name,permission) LOOP
        INSERT INTO public.system_menu(id,name,permission,type,sort,parent_id,path,status,visible,keep_alive,always_show,creator,updater,create_time,update_time,deleted)
        VALUES(nextval('public.system_menu_seq'),e.name,e.permission,3,10,a,'',0,true,false,false,'nocode-migration','nocode-migration',now(),now(),0);
    END LOOP;
END $$;

