-- 同一全局字段的编号由所有应用共享；应用回退不回退计数器。
CREATE TABLE public.nocode_business_counter (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id bigint NOT NULL,
    field_id bigint NOT NULL,
    period_key varchar(16) NOT NULL,
    next_value bigint NOT NULL CHECK(next_value>0),
    creator varchar(64) DEFAULT '', create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '', update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1)),
    UNIQUE(object_id,field_id,period_key)
);
COMMENT ON TABLE public.nocode_business_counter IS '应用业务编号的事务计数器，按全局对象字段和周期隔离';
