-- 有序落库专用的轻量状态；不改变其他 ON_SAVE 的本记录快照语义。
CREATE TABLE public.nocode_ordered_calculation_state (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id bigint NOT NULL,
    field_id bigint NOT NULL,
    signature varchar(64) NOT NULL,
    state varchar(24) NOT NULL,
    cursor_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    total_rows bigint NOT NULL DEFAULT 0,
    updated_rows bigint NOT NULL DEFAULT 0,
    completed_groups bigint NOT NULL DEFAULT 0,
    error_message varchar(2000),
    lock_version bigint NOT NULL DEFAULT 0,
    creator varchar(64) NOT NULL DEFAULT '',
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) NOT NULL DEFAULT '',
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0,
    CONSTRAINT nocode_ordered_calculation_state_field UNIQUE (object_id, field_id),
    CONSTRAINT nocode_ordered_calculation_state_code CHECK (state IN ('PENDING','BACKFILLING','READY','FAILED'))
);
