-- DEC-20260928-01：网盘业务文件入口的用户标记与菜单。前置 V042。
-- 仅新增标记表与菜单定义：收藏/最近访问按用户独立保存于无代码侧（网盘侧标记按空间成员身份过滤，
-- 受管业务节点不在其授权链内），展示时仍按业务授权链重验；菜单只补定义，不向既有角色批量授权。
-- 校验：Flyway verify、表结构检查、菜单唯一性守卫、网盘业务文件专项集成测试（收藏/最近访问/定位链）。

-- 业务文件用户标记：收藏与最近访问；标记不参与任何授权判定
CREATE TABLE public.nocode_biz_file_mark (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    object_id varchar(128) NOT NULL,
    entry_id bigint NOT NULL,
    mark_type varchar(16) NOT NULL,
    access_time timestamp,
    creator varchar(64) NOT NULL DEFAULT '',
    create_time timestamp NOT NULL DEFAULT now(),
    updater varchar(64) NOT NULL DEFAULT '',
    update_time timestamp NOT NULL DEFAULT now(),
    deleted smallint NOT NULL DEFAULT 0 CHECK (deleted IN (0,1)),
    CONSTRAINT nocode_biz_file_mark_type_ck CHECK (mark_type IN ('FAVORITE','RECENT'))
);
-- 部分唯一索引只覆盖未删除行：取消收藏走逻辑删除，再次收藏重新登记
CREATE UNIQUE INDEX nocode_biz_file_mark_uk
    ON public.nocode_biz_file_mark (user_id, entry_id, mark_type) WHERE deleted=0;
-- 列表按（用户、对象、类型）取标记时间倒序前 100
CREATE INDEX nocode_biz_file_mark_list_idx
    ON public.nocode_biz_file_mark (user_id, object_id, mark_type, access_time DESC) WHERE deleted=0;
COMMENT ON TABLE public.nocode_biz_file_mark IS '业务文件用户标记：收藏与最近访问，按用户独立，不改变节点授权也不作为读取依据';
COMMENT ON COLUMN public.nocode_biz_file_mark.entry_id IS '网盘受管节点身份，文件内容仍按业务位置身份重新校验';
COMMENT ON COLUMN public.nocode_biz_file_mark.mark_type IS '标记类型：FAVORITE 收藏、RECENT 最近访问';
COMMENT ON COLUMN public.nocode_biz_file_mark.access_time IS '最近访问时间，仅 RECENT 使用；收藏按登记时间排序';

-- 网盘上级菜单下新增「业务文件」二级菜单（组件 drive/business，权限 drive:business:query）
DO $$
DECLARE
    entry_id bigint;
    menu_count integer;
BEGIN
    SELECT min(id) INTO entry_id
    FROM public.system_menu WHERE deleted=0 AND type=1 AND path='/drive';
    IF entry_id IS NULL THEN
        RAISE EXCEPTION 'Drive entry menu missing; apply drive menu migration first';
    END IF;

    INSERT INTO public.system_menu
    (id,name,permission,type,sort,parent_id,path,icon,component,component_name,status,
     visible,keep_alive,always_show,creator,updater,create_time,update_time,deleted)
    SELECT nextval('public.system_menu_seq'),'业务文件','drive:business:query',2,8,entry_id,
           '/drive/business','FileSearchOutlined','drive/business','DriveBusiness',0,
           true,true,true,'biz-file-menu-migration','biz-file-menu-migration',now(),now(),0
    WHERE NOT EXISTS (
        SELECT 1 FROM public.system_menu existing
        WHERE existing.deleted=0 AND existing.path='/drive/business'
    );

    SELECT count(*) INTO menu_count
    FROM public.system_menu WHERE deleted=0 AND type=2 AND path='/drive/business';
    IF menu_count <> 1 THEN
        RAISE EXCEPTION 'Business file menu incomplete: % of 1 found', menu_count;
    END IF;
END $$;
