-- 数据联动自动更新的反向索引：一行 = 某应用某个发布版本里一个开启自动更新的目标字段。
-- 全部列都由不可变的应用发布快照与对象版本推导，登记后不修改。
CREATE TABLE public.nocode_linkage_trigger (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL,
    application_version integer NOT NULL,
    source_object_id bigint NOT NULL,
    target_object_id bigint NOT NULL,
    target_object_version integer NOT NULL,
    target_field_id bigint NOT NULL,
    anchor varchar(16) NOT NULL,
    anchor_field_id bigint NOT NULL,
    signature varchar(64) NOT NULL,
    creator varchar(64) NOT NULL DEFAULT '',
    create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) NOT NULL DEFAULT '',
    update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0,
    CONSTRAINT nocode_linkage_trigger_anchor CHECK (anchor IN ('CURRENT_RECORD', 'RECORD_KEY')),
    CONSTRAINT nocode_linkage_trigger_field
        UNIQUE (application_id, application_version, target_object_id, target_field_id)
);
CREATE INDEX nocode_linkage_trigger_source
    ON public.nocode_linkage_trigger (application_id, application_version, source_object_id)
    WHERE deleted = 0;
CREATE INDEX nocode_linkage_trigger_source_any
    ON public.nocode_linkage_trigger (source_object_id) WHERE deleted = 0;
CREATE INDEX nocode_linkage_trigger_target_any
    ON public.nocode_linkage_trigger (target_object_id) WHERE deleted = 0;
