-- 应用对数据对象的「自动跟随」开关与状态。前置 V045。
-- 独立于应用草稿与发布版本：拨动立即生效，不随应用回退。没有行 = 默认开启且正常跟随。
-- 影响范围：新增两张表与一条定时任务登记；不改任何现有表与数据。
-- 应用或对象的行被物理删除时（正式环境只做逻辑删除；集成测试夹具清理会物理删除）跟随状态与日志随之删除。
-- 校验：SELECT count(*) FROM public.nocode_application_object_follow; 迁移后应为 0。
--       SELECT count(*) FROM public.infra_job WHERE handler_name='applicationFollowRetryJob' AND deleted=0; 应为 1。
CREATE TABLE public.nocode_application_object_follow (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES public.nocode_application(id) ON DELETE CASCADE,
    object_id bigint NOT NULL REFERENCES public.nocode_object(id) ON DELETE CASCADE,
    enabled boolean NOT NULL DEFAULT true,
    state varchar(16) NOT NULL DEFAULT 'FOLLOWING',
    pending_version integer,
    pending_code varchar(24),
    pending_reason varchar(1000),
    followed_version integer,
    followed_at timestamp(6),
    lock_version integer NOT NULL DEFAULT 0,
    creator varchar(64) DEFAULT '', create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '', update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1)),
    CONSTRAINT nocode_application_object_follow_uk UNIQUE (application_id, object_id),
    CONSTRAINT nocode_application_object_follow_state CHECK (state IN ('FOLLOWING','PENDING')),
    CONSTRAINT nocode_application_object_follow_code CHECK (pending_code IS NULL OR pending_code IN ('IN_FLIGHT','VALIDATION','ERROR')),
    CONSTRAINT nocode_application_object_follow_pending
        CHECK ((state = 'PENDING') = (pending_version IS NOT NULL AND pending_code IS NOT NULL))
);
CREATE INDEX nocode_application_object_follow_object ON public.nocode_application_object_follow(object_id);
CREATE INDEX nocode_application_object_follow_pending_ix ON public.nocode_application_object_follow(state) WHERE state = 'PENDING' AND deleted = 0;
COMMENT ON TABLE public.nocode_application_object_follow IS '应用对数据对象的自动跟随开关与状态；没有行表示默认开启';

CREATE TABLE public.nocode_application_object_follow_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id bigint NOT NULL REFERENCES public.nocode_application(id) ON DELETE CASCADE,
    object_id bigint NOT NULL REFERENCES public.nocode_object(id) ON DELETE CASCADE,
    from_version integer NOT NULL,
    to_version integer NOT NULL,
    application_version_before integer,
    application_version_after integer,
    outcome varchar(16) NOT NULL,
    pending_code varchar(24),
    reason varchar(1000),
    trigger_kind varchar(24) NOT NULL,
    plan_id uuid,
    creator varchar(64) DEFAULT '', create_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater varchar(64) DEFAULT '', update_time timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1)),
    CONSTRAINT nocode_application_object_follow_log_outcome CHECK (outcome IN ('FOLLOWED','PENDING')),
    CONSTRAINT nocode_application_object_follow_log_trigger
        CHECK (trigger_kind IN ('OBJECT_PUBLISH','SWITCH_ON','MANUAL','RETRY_JOB','APPLICATION_PUBLISH','MIGRATION'))
);
CREATE INDEX nocode_application_object_follow_log_app ON public.nocode_application_object_follow_log(application_id, object_id, id);
CREATE INDEX nocode_application_object_follow_log_plan ON public.nocode_application_object_follow_log(plan_id) WHERE plan_id IS NOT NULL;
COMMENT ON TABLE public.nocode_application_object_follow_log IS '自动跟随的逐次结果，只增不改';

-- 定时重试「跟随待处理」。迁移后在定时任务页执行一次“同步任务”以创建调度实例（同 V044 的做法）。
INSERT INTO public.infra_job
    (id, powerjob_job_id, name, status, handler_name, handler_param,
     cron_expression, retry_count, retry_interval, monitor_timeout,
     creator, create_time, updater, update_time, deleted)
SELECT nextval('public.infra_job_seq'), NULL, '应用自动跟随重试', 1,
       'applicationFollowRetryJob', '', '0 */10 * * * ?', 0, 0, 300000,
       'application-follow-migration', now(), 'application-follow-migration', now(), 0
WHERE NOT EXISTS (
    SELECT 1 FROM public.infra_job WHERE handler_name='applicationFollowRetryJob' AND deleted=0
);
