-- 独立仪表板首批拥有者制作/发布闭环；数据读取仍沿用数据集授权，未向普通角色自动授予权限。
CREATE TABLE public.nocode_report_dashboard (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name varchar(80) NOT NULL, owner_id bigint NOT NULL,
 draft_json jsonb NOT NULL,draft_checksum varchar(64) NOT NULL,
 lock_version integer NOT NULL DEFAULT 1 CHECK(lock_version>0),published_version integer CHECK(published_version>0),
 creator varchar(64) NOT NULL DEFAULT '',create_time timestamp NOT NULL DEFAULT now(),
 updater varchar(64) NOT NULL DEFAULT '',update_time timestamp NOT NULL DEFAULT now(),deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1))
);
CREATE INDEX nocode_report_dashboard_owner_idx ON public.nocode_report_dashboard(owner_id,update_time DESC,id DESC) WHERE deleted=0;
CREATE TABLE public.nocode_report_dashboard_version (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dashboard_id bigint NOT NULL REFERENCES public.nocode_report_dashboard(id),version_no integer NOT NULL CHECK(version_no>0),
 definition_json jsonb NOT NULL,checksum varchar(64) NOT NULL,request_id varchar(80) NOT NULL,
 creator varchar(64) NOT NULL DEFAULT '',create_time timestamp NOT NULL DEFAULT now(),
 updater varchar(64) NOT NULL DEFAULT '',update_time timestamp NOT NULL DEFAULT now(),deleted smallint NOT NULL DEFAULT 0 CHECK(deleted IN (0,1)),
 UNIQUE(dashboard_id,version_no),UNIQUE(dashboard_id,creator,request_id)
);
COMMENT ON TABLE public.nocode_report_dashboard IS '独立仪表板草稿；拥有者不自动获得业务读取权';
COMMENT ON TABLE public.nocode_report_dashboard_version IS '仪表板不可变发布版本，引用固定数据集版本';
INSERT INTO public.system_menu(id,name,permission,type,sort,parent_id,path,icon,component,component_name,status,visible,keep_alive,always_show,creator,updater,create_time,update_time,deleted)
SELECT nextval('public.system_menu_seq'),'仪表板','nocode:report:query',2,0,id,'/nocode/report-center/dashboards','DashboardOutlined','nocode/report-center/dashboards','NocodeReportDashboards',0,true,false,true,'report-dashboard-migration','report-dashboard-migration',now(),now(),0
FROM public.system_menu WHERE path='/nocode/report-center' AND deleted=0;
