/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumb: typeof import('./src/components/common/AppBreadcrumb.vue')['default']
    AppIcon: typeof import('./src/components/AppIcon.vue')['default']
    AssigneeAvatar: typeof import('./src/components/AssigneeAvatar.vue')['default']
    BreadcrumbNav: typeof import('./src/components/BreadcrumbNav.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    Cropper: typeof import('./src/components/cropper/cropper.vue')['default']
    CropperAvatar: typeof import('./src/components/cropper/cropper-avatar.vue')['default']
    CropperModal: typeof import('./src/components/cropper/cropper-modal.vue')['default']
    DeptSelector: typeof import('./src/components/DeptSelector.vue')['default']
    FeedbackWidget: typeof import('./src/components/system-feedback/FeedbackWidget.vue')['default']
    FieldRenderer: typeof import('./src/components/FieldRenderer.vue')['default']
    IconSelector: typeof import('./src/components/IconSelector.vue')['default']
    InfraUpload: typeof import('./src/components/InfraUpload.vue')['default']
    MemberSelect: typeof import('./src/components/MemberSelect.vue')['default']
    MessageEditor: typeof import('./src/components/MessageEditor.vue')['default']
    MobileNavigation: typeof import('./src/components/navigation/MobileNavigation.vue')['default']
    NavigationTabs: typeof import('./src/components/navigation/NavigationTabs.vue')['default']
    OsConditionGroupRenderer: typeof import('./src/components/ucp-table-page/OsConditionGroupRenderer.vue')['default']
    OsDynamicSearch: typeof import('./src/components/ucp-table-page/OsDynamicSearch.vue')['default']
    OsModalForm: typeof import('./src/components/ucp-modal-form/OsModalForm.vue')['default']
    OsSelectInvert: typeof import('./src/components/OsSelectInvert.vue')['default']
    OsTablePage: typeof import('./src/components/ucp-table-page/OsTablePage.vue')['default']
    PaginationBar: typeof import('./src/components/PaginationBar/index.vue')['default']
    PlatformMenuFields: typeof import('./src/components/PlatformMenuFields.vue')['default']
    RoleSelector: typeof import('./src/components/RoleSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenshotEditor: typeof import('./src/components/system-feedback/ScreenshotEditor.vue')['default']
    TableRelationDesigner: typeof import('./src/components/TableRelationDesigner.vue')['default']
    TiptapEditor: typeof import('./src/components/TiptapEditor.vue')['default']
    UserSelector: typeof import('./src/components/UserSelector/index.vue')['default']
    UserSelectorTrigger: typeof import('./src/components/UserSelectorTrigger.vue')['default']
  }
}
