import { chromium, expect } from '@playwright/test'
import { mkdir, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
const out = resolve('tests/test-results/data-form-enhancement')
await mkdir(out, { recursive: true })
const browser = await chromium.launch({ headless: true, channel: process.env.FORM_BROWSER || 'chrome' })
const page = await browser.newPage({ viewport: { width: 1280, height: 1000 } })
page.setDefaultTimeout(8000)
const errors = [],
  checks = []
page.on('pageerror', e => errors.push(e.message))
page.on('response', r => {
  if (r.status() >= 400) errors.push(`${r.status()} ${r.url()}`)
})
await page.route('**/nocode/design/page*', route => route.fulfill({ json: { code: 0, data: { list: [], total: 0 } } }))
try {
  await page.goto(process.env.FORM_ENHANCEMENT_URL || 'http://127.0.0.1:5196')
  await page.locator('.calculation-editor .ant-select-selector').first().click()
  await page.getByText('按条件查找与汇总', { exact: true }).click()
  await page.getByRole('button', { name: '添加条件', exact: true }).click()
  await expect(page.getByTestId('calculation')).toContainText('"mode":"LOOKUP"')
  await page.getByText('本记录保存时重算', { exact: true }).click()
  await expect(page.getByTestId('calculation')).toContainText('"updateMode":"ON_SAVE"')
  checks.push('计算来源、更新方式和条件编辑')
  await page.locator('h1').click()
  await expect(page.locator('.ant-select-dropdown:visible')).toHaveCount(0)
  await page.screenshot({ animations: 'disabled', path: resolve(out, 'calculation.png'), fullPage: true })
  await page.getByText('数据权限', { exact: true }).click()
  await expect(page.getByTestId('scope')).toContainText('CURRENT_DEPARTMENT_TREE')
  await page.getByRole('button', { name: '添加条件组', exact: true }).click()
  await expect(page.locator('.scope-group')).toHaveCount(1)
  await page.locator('.scope-group').getByRole('button', { name: '添加条件', exact: true }).click()
  await expect(page.locator('.scope-group .scope-condition')).toHaveCount(1)
  checks.push('部门动态范围及嵌套条件组')
  await page.locator('h1').click()
  await expect(page.locator('.ant-select-dropdown:visible')).toHaveCount(0)
  await page.screenshot({ animations: 'disabled', path: resolve(out, 'scope.png'), fullPage: true })
  await page.getByText('字典范围', { exact: true }).click()
  const filter = page.locator('section > .ant-select').last()
  await expect(filter.getByTitle('办公资产', { exact: true })).toBeVisible()
  await filter.click()
  await expect(page.locator('.ant-select-dropdown:visible').getByText('办公资产', { exact: true })).toBeVisible()
  await expect(page.locator('.ant-select-dropdown:visible').getByText('生产资产', { exact: true })).toBeVisible()
  await expect(page.locator('.ant-select-dropdown:visible').getByText('其他资产', { exact: true })).toHaveCount(0)
  await page.locator('.ant-select-dropdown:visible').getByText('生产资产', { exact: true }).click()
  await expect(page.getByTestId('filter-value')).toContainText('["A","B"]')
  await expect(filter.getByTitle('办公资产', { exact: true })).toBeVisible()
  await expect(filter.getByTitle('生产资产', { exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByTestId('query')).toContainText('"value":["A","B"]')
  checks.push('运行筛选只展示固定字典范围')
  checks.push('固定多值范围兼容单个默认值回显并可继续多选')
  await page.locator('h1').click()
  await expect(page.locator('.ant-select-dropdown:visible')).toHaveCount(0)
  await page.screenshot({ animations: 'disabled', path: resolve(out, 'dictionary.png'), fullPage: true })
  await page.getByText('超链接', { exact: true }).click()
  await expect(page.getByRole('link', { name: '资产使用说明' })).toHaveAttribute('href', 'https://example.com/manual')
  await expect(page.getByRole('link', { name: '资产使用说明' })).toHaveAttribute('rel', 'noopener noreferrer')
  await page.getByRole('textbox', { name: '链接地址', exact: true }).fill('javascript:alert(1)')
  await expect(page.getByRole('alert')).toContainText('有效')
  await expect(page.getByRole('link')).toHaveCount(0)
  await page.getByRole('textbox', { name: '链接地址', exact: true }).fill('https://example.com/manual')
  checks.push('超链接录入、展示及非法协议拒绝')
  await page.locator('h1').click()
  await expect(page.locator('.ant-select-dropdown:visible')).toHaveCount(0)
  await page.screenshot({ animations: 'disabled', path: resolve(out, 'hyperlink.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  for (const label of ['公式配置', '数据权限', '字典范围', '超链接']) {
    await page.getByText(label, { exact: true }).click()
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1)).toBe(true)
  }
  checks.push('390px 窄屏无水平溢出')
  await expect(page.locator('.ant-notification-notice-error')).toHaveCount(0)
  expect(errors).toEqual([])
  await writeFile(resolve(out, 'result.json'), JSON.stringify({ passed: true, checks, errors }, null, 2))
  console.log(JSON.stringify({ passed: true, checks, errors }, null, 2))
} finally {
  await browser.close()
}
