<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.lingan</groupId>
        <artifactId>ucp</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>ucp-module-msg</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>ucp-module-msg-api</module>
        <module>ucp-module-msg-core</module>
    </modules>


</project>