<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.lingan</groupId>
        <artifactId>ucp</artifactId>
        <version>${revision}</version>
    </parent>
    <properties>
        <maven.test.skip>false</maven.test.skip>
    </properties>
    <artifactId>ucp-nocode</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>ucp-nocode-api</module>
        <module>ucp-nocode-metadata</module>
        <module>ucp-nocode-schema</module>
        <module>ucp-nocode-application</module>
        <module>ucp-nocode-report</module>
        <module>ucp-nocode-work</module>
        <module>ucp-nocode-runtime</module>
        <module>ucp-nocode-workflow</module>
        <module>ucp-nocode-web</module>
        <module>ucp-nocode-tools</module>
    </modules>
</project>
